### ISSUE TITLE
Add templates for Stride

### ISSUE THREAD

**Issue by jacobjohnston** [tcplugins/tcWebHooks#100]
It looks like you're already working on a customizable header to allow Stride's API token authorization, but it'd be really nice if you provided us with some nice Stride templates at the same time :-)

**Comment by netwolfuk** [comment]
woot! Issue number 100. Lucky you.

Yeah. I had started working on custom headers, and also a project to allow [sharing of templates](https://github.com/tcplugins/tcWebHooksTemplates). But then forgot to push to github before I left for six weeks travelling for work.

The plan for that project is to be able to share your templates with other users via a pull request. I have made some small tweaks to the API and written an export script (an early version was pushed). I have started on the import script, but it's not ready yet. obviously I didn't get to work on that whilst away either due to lack of a push :-(

Whilst away I did do some work on the testing ticket #79 but I'm back now (albiet a bit jet-lagged), so will dig out the branch for #95 and rebase that on top.

I might get some time on the weekend to progress it, but the code is pretty yuck at the integration point, so I am needing to do some cleanup there.

**Comment by netwolfuk** [comment]
I have a simple template working.
![image](https://user-images.githubusercontent.com/88687/38666967-550173ec-3e94-11e8-93c0-65b32d7d222b.png)

**Comment by netwolfuk** [comment]
If you see a nice looking Stride message, can you add screenshot of it, and I could try to replicate it.

**Comment by netwolfuk** [comment]
This is useful for building payloads:
https://developer.atlassian.com/cloud/stride/apis/document/playground/

**Comment by jacobjohnston** [comment]
I think the "Panel" node type seems appropriate for these sorts of notifications. However, for whatever reason, it doesn't look like Stride has implemented the "error" or "success" panel types in the Stride client yet (even though they are supported [according to the documentation](https://developer.atlassian.com/cloud/stride/apis/document/nodes/panel/)). However, the warning, info, and note types are implemented.

Here's what that looks like in the room:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/1703107/38688383-c8e7c8c2-3e2d-11e8-8cab-811fa0bf8dc8.png">


Here's the JSON I'm sending the Stride API:

    {
        "body": { "version":1,"type":"doc","content":[{
                  "type": "panel",
                  "attrs": {
                    "panelType": "info"
                  },
                  "content": [
                    {
                      "type": "heading",
                      "attrs": {
                        "level": 3
                      },
                      "content": [
                        {
                          "type": "text",
                          "text": "Build Succeeded"
                        }
                      ]
                    },
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "type": "text",
                          "text": "Project Name: ",
                          "marks": [
                            {
                              "type": "strong"
                            }
                          ]
                        },
                        {
                          "type": "text",
                          "text": "${projectName}"
                        }
                      ]
                    },
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "type": "text",
                          "text": "Build Name: ",
                          "marks": [
                            {
                              "type": "strong"
                            }
                          ]
                        },
                        {
                          "type": "text",
                          "text": "${buildName}"
                        }
                      ]
                    },
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "type": "text",
                          "text": "Triggered By: ",
                          "marks": [
                            {
                              "type": "strong"
                            }
                          ]
                        },
                        {
                          "type": "text",
                          "text": "${triggeredBy}"
                        }
                      ]
                    }
                  ]
                }
            ]
        }
    }

**Comment by netwolfuk** [comment]
Thanks. I will play with that over the weekend if I get chance.

**Comment by netwolfuk** [comment]
Here is a first go at a [simple stride template](https://github.com/tcplugins/tcWebHooksTemplates/tree/master/webhook-templates/stride_simple). Not a box model, but certainly something we can build on.
Instructions for installing templates from that repo are [here](https://github.com/tcplugins/tcWebHooksTemplates):
You're welcome to enhance it or copy it to build your box one. Then you can export it and share it on the that repo. You can edit it in the UI as per the [WebHook-Templates-:-Web-UI](https://github.com/tcplugins/tcWebHooks/wiki/WebHook-Templates-%3A-Web-UI) page.

The test version I just posted on the other ticket works for import/export via the REST API, and has support for Bearer auth, and Headers.

I imagine a full version of the box one would have content more like this one I did for slack: 
![image](https://user-images.githubusercontent.com/88687/33641251-a070628e-da99-11e7-8060-a454b535d52a.png)
It might not look the same, but could have similar content.

**Comment by netwolfuk** [comment]
Can you have more than one column in the Stride box?

**Comment by netwolfuk** [comment]
Cool. That's a nice addition. Do you want to export it and submit a pull request or attach it to this issue?

**Comment by netwolfuk** [comment]
Curl -k tells it to ignore cert checking.

**Comment by netwolfuk** [comment]
Added issue #101. Will be on milestone 1.2

**Comment by netwolfuk** [comment]
Added create issue https://github.com/tcplugins/tcWebHooksTemplates/issues/1 to allow setting of `-k` in import/export scripts.

Also updated the curl example in the readme to include `-k`

**Comment by netwolfuk** [comment]
I have pushed your changes and a few other bits to the tcplugins/tcWebHooksTemplates repo .

> Updated stride template.
> Thanks to @jacobjohnston for formatting updates.
>
> Format changes
> - Added the project name (and a link)
> - Put a space between "Build" and "#"
> - Changed the emoji used in failed from warning to :failed:
>
> Meta data changes
> - Change description to include "Atlassian"
> - Set rank to 100 (rather than 1)
> - Added tooltip text
> - Removed support for "Responsibility Changed", since it was not
working.
> - Updated description in readme.md

**Comment by jacobjohnston** [comment]
Great! By the way, you may want to update your description in the TeamCity plugin repository to mention the sorts of things you have templates for. I was searching for phrases like "TeamCity Stride" for a couple of months with no luck - it took me a while to find your plugin because I wasn't necessarily thinking of using webhooks (even though it seems obvious in hindsight). I think there will be a lot of people searching for this solution for Stride now that their HipChat systems are being deprecated.

**Comment by netwolfuk** [comment]
Ah. Yeah. That's a good point. I'll do that and then write a blog post about it.
