### ISSUE TITLE
Wiki doesn't have correct information for editing webhook templates.

### ISSUE THREAD

**Issue by coreyman** [tcplugins/tcWebHooks#104]
https://github.com/tcplugins/tcWebHooks/wiki/WebHook-Templates-%3A-Creating%2C-Reading%2C-Editing%2C-Deleting

On your wiki page you say you can edit the webhook-templates.xml file stored in BuildServer/config/ using a text editor, there was no such file webhook-templates.xml on my filesystem at all. I had to install the REST API thing to be able to edit webhook templates.

**Comment by netwolfuk** [comment]
Good point. The file won't exist unless you already have a local webhook template defined.
The easiest way to create that file would be to copy one of the test ones. Eg, https://github.com/tcplugins/tcWebHooks/blob/master/tcwebhooks-core/src/test/resources/webhook-templates.xml

**Comment by coreyman** [comment]
Can you update the wiki to state that? Also exactly where to copy it to? I assume "BuildServer" in the path ``` BuildServer/conf ``` is your teamcity directory but it's not clear to me.

**Comment by netwolfuk** [comment]
Sure can. I'll close this ticket when done. Thanks for taking the time to raise the issue.

**Comment by netwolfuk** [comment]
A new page created: https://github.com/tcplugins/tcWebHooks/wiki/WebHook-Templates-:-webhook-templates-xml
And wiki updated to link to it.
