### ISSUE TITLE
801 :: Error Read timed out occurred while attempting to execute Webhook

### ISSUE THREAD

**Issue by wadinj** [tcplugins/tcWebHooks#105]
Hi,

First thanks for this plugin which is really useful. We are facing some issue with the Legacy JSON payload. Sometimes, we got this error : 801 :: Error Read timed out occurred while attempting to execute Webhook.
This seems to be raise because the payload sent is too long and then take time to be processed.

As a workaround, I'm looking at Elasticsearch output payload to send only the field that we need and not the whole payload.

Do you know why this exception is raised ? Is my interpretation good ?

**Comment by netwolfuk** [comment]
Yeah. That would make sense. 8xx errors are http connection and/or TCP type errors. 9xx are webhook configuration or template error, and anything below are the response from the sever.

I guess it could be taking a while to process the data. It's not a lot of data by modern web standards, but it's probably a lot more than the one field you need.

I'd probably need to look at the log to see more detail.

Having a dedicated template is the best option, or use the tailored json format and define your full JSON string as a webhook.body build parameter.

**Comment by netwolfuk** [comment]
The other thing to check would be connectivity. The webhook will be sent from the TeamCity server. Does it have a routing issue or firewall preventing the sever from getting a response?

From memory, the responses that java gives for these sorts of issues are fairly generic.

Try connecting from the server to the URL using curl or a browser or something like that.

**Comment by wadinj** [comment]
All others webhook works, but when we got a payload over 30k line (changes into the payload can take lot of place when there's a merge into master) we got this issue. I check the network route between teamcity server and the target machine but nothing infer with the payload and block it.

We don't need the change list information (which takes lot of place) into the JSON legacy payload. Do you know if there's a way to remove it frome the legacy payload while we put in place the Elasticsearch custom payload ?

**Comment by netwolfuk** [comment]
Ah, yes. The changelist would certainly cause the payload to be bigger. 
It would be quite easy to build your own custom template with just the fields you want from the legacy JSON payload. See details here: https://github.com/tcplugins/tcWebHooks/wiki/WebHook-Templates-%3A-Web-UI

Sorry, I can't think of a way to exclude the changes from the legacy payload.

**Comment by wadinj** [comment]
Ok thanks, we'll move to that then. I close this issue.

Thanks,
Jonathan
