### ISSUE TITLE
Include Templates for Microsoft Teams

### ISSUE THREAD

**Issue by jacobjohnston** [tcplugins/tcWebHooks#108]
After the announcement that Slack will be shutting down HipChat/Stride, my company decided to move over to Microsoft Teams (as we already have Office 365 accounts). Turns out tcWebHooks is excellent at supporting Microsoft Teams as well. It'd be excellent if templates were included out-of-the-box for Microsoft Teams.

I created a couple templates for Microsoft Team's Message JSON format and have attached them to this issue.
[Microsoft Teams Templates.zip](https://github.com/tcplugins/tcWebHooks/files/2246845/Microsoft.Teams.Templates.zip)

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1703107/43483026-3bf570ac-94bf-11e8-9923-471732b3fc92.png">

**Comment by netwolfuk** [comment]
They look terrific. Thanks. There are also some here: https://github.com/tcplugins/tcWebHooksTemplates

Maybe you could submit a pull request to update those? The one there has no screen shot so I never knew what they looked like.

The atlassian announcement surprised me.

**Comment by netwolfuk** [comment]
Or create an alternative template there.

**Comment by netwolfuk** [comment]
Hi @jacobjohnston Just wondering if you had a chance to think about a PR for these?

**Comment by netwolfuk** [comment]
Thanks for this. I have added it here: https://github.com/tcplugins/tcWebHooksTemplates/tree/master/webhook-templates/microsoft-teams-2

And will add this one and the other teams one to the next release.

**Comment by netwolfuk** [comment]
Added both MS teams templates to the release.
