### ISSUE TITLE
Make sure a message is displayed when editing _Root webhooks if not Administrator

### ISSUE THREAD

**Issue by savulchik** [tcplugins/tcWebHooks#11]
I would like to configure webhooks for all projects in Teamcity in one place. I suppose the Root project is the right place to do it but configuration is unavailable:
![selection_001](https://cloud.githubusercontent.com/assets/187893/10133801/d6504d54-65f9-11e5-879d-2a311996b326.png)
Is it possible to implement webhooks configuration for the Root project?

**Comment by netwolfuk** [comment]
Yes, but you need to be the Administrator I think. Also need to be running at least https://github.com/tcplugins/tcWebHooks/releases/tag/v0.9.35.72

**Comment by savulchik** [comment]
@netwolfuk, thanks. Indeed, it works under System Administrator.

**Comment by netwolfuk** [comment]
I'll have a look and see why you didn't get a nicer message informing you that you needed Admin rights.

**Comment by netwolfuk** [comment]
I'll close this. It's in the 1.1 versions (custom-templates, custom-velocity-templates). 
I won't add it to 0.9 (master)
