### ISSUE TITLE
Incompatible with TeamCity 2018.1.2

### ISSUE THREAD

**Issue by htonheim** [tcplugins/tcWebHooks#112]
## Expected Behavior
TeamCity should work.

## Current Behavior
TeamCity UI breaks down completely. teamcity-server.log is full of "Unexpected response while executing internal Rest API request". See https://youtrack.jetbrains.com/issue/TW-56626.

## Steps to Reproduce (for bugs)
1. Upgrade to TeamCity 2018.1.2.
2. Install TcWebHooks 1.1-alpha17.235.3543.
3. Watch the world burn.

## Your Environment
* tcWebHooks Version: 1.1-alpha17.235.354
* TeamCity Version: 2018.1.2.
* TeamCity server Operating System: Windows 2008R2
* Are you using a WebHook Template?: No

**Comment by netwolfuk** [comment]
Thanks for the heads up. Updating TeamCity to 2018.1.2 now to check.

**Comment by netwolfuk** [comment]
Hi @htonheim. 

As mentioned on the YouTrack ticket, removing the **Web Hooks REST API (tcWebHooks)** plugin from the **Administation -> Plugins** page on the TeamCity server and restarting TeamCity will resolve this issue. You do not need to uninstall the **Web Hooks (tcWebHooks)** plugin.

I am testing a fix for this issue at the moment, and hope to do a release shortly.

**Comment by netwolfuk** [comment]
Issue is resolved by new release.
