### ISSUE TITLE
MessageML v1 or v2 support

### ISSUE THREAD

**Issue by wbagdon** [tcplugins/tcWebHooks#119]
Trying to figure out how I can use this plugin with the MessageML v1 or v2 format (seems proprietary to messenger Symphony):
https://github.com/symphonyoss/App-Integrations-Universal/blob/dev/README.md

I may be overlooking some features, but I think it is right now only possible to send JSON.

MessageMLv1 would require sending a specific formatted XML:
https://rest-api.symphony.com/docs/message-format/

MessageMLv2 would require sending XML + JSON in form-data:
https://rest-api.symphony.com/v1.52/docs/messagemlv2

Not sure if this is way out of the scope of this project at this time.
If you can think of any workarounds I'm all ears on that.

Thanks!

**Comment by netwolfuk** [comment]
I just tested this with a manual header added:
```
      <headers>
        <header name="Content-Type" value="application/xml; charset=UTF-8" />
      </headers>
```

It appears to be quite good. The header is overriden correctly as `Content-Type: application/xml`

**Comment by wbagdon** [comment]
That works really well!

I'm going to start digging around the code to get familiar with it.
Hopefully I can add in support for XML templates and form-data templates.
Any suggestions for where to start?

**Comment by wbagdon** [comment]
I was able to add the `xmlTemplate` format today.
I have to work through some red tape with my company, then I'll post the changes to GitHub.

**Comment by netwolfuk** [comment]
Cool! Did you manage to do a build and a test install on a TeamCity instance?

**Comment by netwolfuk** [comment]
BTW, until we get the UI working, you could create the template as a JSON one, and then edit `webhook-templates.xml` on the server and change the `format` to `xmlTemplate`. The file will be reloaded after a second or two, and then you could create a new webhook without the custom header and test it.
You also might be able to GET, edit the file and the PUT it again via the rest API to update that field.

**Comment by netwolfuk** [comment]
/me wishes there was some docs on how to use the REST API. ☹️

**Comment by wbagdon** [comment]
Yeah I have that and the UI working.
Created a few bugs that I'm working out.
I'm not an expert in JavaScript so it's taking me a bit to figure out how everything is working, but my additions are basically functional.

**Comment by netwolfuk** [comment]
Haha. Yeah. That JavaScript is not my finest work. I'm far from an expert myself.

**Comment by netwolfuk** [comment]
I need to learn more about how to structure js code to use inheritance or something. There is a lot of repeated code in there, and it feels yucky. It will be nice when es2015 is standard in browsers, and we can use classes in js.

**Comment by netwolfuk** [comment]
Hi @wbagdon. Did you get a chance to get your pr signed off?

I'm looking at making some large changes in the same code, and would be easier with your change merged in sooner rather than later.

**Comment by wbagdon** [comment]
Should be able to get it in this week

**Comment by wbagdon** [comment]
Go ahead an make your changes, I discovered that I've broken some preview logic and I'll need to go through and fix this. I should be able to recreate what I've done on top off your changes.

**Comment by netwolfuk** [comment]
Ok. My focus this week is on getting 1.1 out, so will do that. Work looks busy for most of the month and then I'll get to look at the list of 1.2 items (including this) after that.

**Comment by netwolfuk** [comment]
Hi. 

I've now done the work to support different types of `WebHookPayload` types.
You should just be able to create your template type and register it in spring.

See 13c366f for what I did to create the `x-www-urlencoded` one.

**Comment by netwolfuk** [comment]
This will be released as part of version 1.2.0

**Comment by netwolfuk** [comment]
@wbagdon  Do you want to create an example Symphony template which we can bundle with the 1.2.0 release?

**Comment by netwolfuk** [comment]
BTW, the latest builds off master, now have template import/export support from the UI.

**Comment by wbagdon** [comment]
I don't think it's worthwhile to bundle an example with the plug-in. Thanks for knocking this out!

**Comment by netwolfuk** [comment]
ok. If you do get something working, would you mind submitting a PR to the [tcWebHooksTemplates](https://github.com/tcplugins/tcWebHooksTemplates) project?

FYI, at my last job, we had TeamCity and Symphony. So maybe it's not as rare as you think. ;-)

**Comment by wbagdon** [comment]
Yeah, we're not fully running with it yet so I'll submit something when I have a concrete message

**Comment by netwolfuk** [comment]
1.2.0 alpha.1 released which includes this fix.
