### ISSUE TITLE
Missing Webhook notification when manually set build to success / fail

### ISSUE THREAD

**Issue by Rainer981** [tcplugins/tcWebHooks#121]
## Expected Behavior
When a build failed, I can manually change the status from failed to success. This makes sense, when TeamCity is calling for example Octopus. On Octopus we retry the step and everything is alright, except the failure status in TeamCity.
I would expect, that also manually changes in status will be triggered.

## Current Behavior
Currently any changes from failure to success and success to failure is not being notified.

## Steps to Reproduce (for bugs)
1. Open build view
2. Click on actions
3. Click on "mark as successful"

## Your Environment

* tcWebHooks Version: 1.1-RC2.246.379
* TeamCity Version: 2017.2.2 (build 50909)
* TeamCity server Operating System: Windows Server
* Are you using a WebHook Template?: elasticsearch

**Comment by netwolfuk** [comment]
I wasn't aware of this feature. I have [asked the teamcity team](https://youtrack.jetbrains.com/issue/TW-57385).

**Comment by netwolfuk** [comment]
@Rainer981 

Would you expect this to be a separate event type? So that one can decide to subscribe to this event specifically.

Or just an event sent because because of a subscribtion to "buildFailed, buildSuccessful"

**Comment by netwolfuk** [comment]
I have implemented the latter. Marking a build as failed or successful simply sends a normal build finished event, and will therefore handled "success, fixed, fail and broken" events correctly.

**Comment by netwolfuk** [comment]
Build 285 and newer support this feature if you'd like to try it before 1.2.0 is released.

https://teamcity.jetbrains.com/viewType.html?buildTypeId=WebHooksAndOtherPlugins_TcWebHooks&branch_WebHooksAndOtherPlugins=%3Cdefault%3E&tab=buildTypeStatusDiv

Just login as guest to download the artifacts.

**Comment by netwolfuk** [comment]
1.2.0 alpha.1 released which includes this fix.
