### ISSUE TITLE
com.google.gson.JsonSyntaxException

### ISSUE THREAD

**Issue by gassanpavel** [tcplugins/tcWebHooks#124]
[teamcity-server.log](https://github.com/tcplugins/tcWebHooks/files/2652628/teamcity-server.log)
## Expected Behavior
Sending notifications about Failed builds

## Current Behavior
For some projects, no notifications sconfigured in WebHooks are sent, in the WebHooks settings configured for project in the preview error
"An error occured building the payload preview
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence line 10 column 90 path $ .attaments [0] .fields [0] .value "

## Steps to Reproduce (for bugs)
- set up a webhook for the project
- select Template Slack.com JSON template
- in webhook config select Trigger when build Fails
- go to the Preview & Test tab, select a build with the Failed status

## Your Environment
* tcWebHooks Version: 1.1.261.385
* TeamCity Version: 2018.1.2 (build 58537)
* TeamCity server Operating System: Windows Server 2012 R2 Datacenter
* Are you using a WebHook Template?:  Slack.com JSON template

## Example Configuration (xml)

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<webhook-templates>
    <webhook-template id="slack.com" enabled="true" rank="100" format="jsonTemplate">
        <default-template use-for-branch-template="false">{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "${capitalise(buildStateDescription)} : ${buildName} &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "${capitalise(buildStateDescription)} : ${buildName} build #${buildNumber}", 
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus} (${buildStateDescription})" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;" },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</default-template>
        <default-branch-template>{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "${capitalise(buildStateDescription)} : ${buildName} [${branchDisplayName}] &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "${capitalise(buildStateDescription)} : ${buildName} [${branchDisplayName}] build #${buildNumber}", 
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus} (${buildStateDescription})" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Branch", "value" : "${branchDisplayName}", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</default-branch-template>
        <template-description>Slack.com JSON templates</template-description>
        <template-tool-tip>Supports the slack.com JSON webhooks endpoint</template-tool-tip>
        <preferred-date-format></preferred-date-format>
        <templates max-id="5">
            <template id="1">
                <template-text use-for-branch-template="false">{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "Failed (broken) : ${buildName} &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "Failed (broken) : ${buildName} build #${buildNumber}",
            "color": "danger",
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</template-text>
                <branch-template-text>{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "Failed (broken) : ${buildName} [${branchDisplayName}] &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "Failed (broken) : ${buildName} [${branchDisplayName}] build #${buildNumber}", 
            "color": "danger",
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Branch", "value" : "${branchDisplayName}", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</branch-template-text>
                <states>
                    <state type="buildBroken" enabled="true"/>
                </states>
            </template>
            <template id="2">
                <template-text use-for-branch-template="false">{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "Success (fixed) : ${buildName} &lt;${buildStatusUrl}|build #${buildNumber}&gt;", 
            "fallback": "Success (fixed) : ${buildName} build #${buildNumber}", 
            "color": "good",
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</template-text>
                <branch-template-text>{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "Success (fixed) : ${buildName} [${branchDisplayName}] &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "Success (fixed) : ${buildName} [${branchDisplayName}] build #${buildNumber}", 
            "color": "good",
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Branch", "value" : "${branchDisplayName}", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</branch-template-text>
                <states>
                    <state type="buildFixed" enabled="true"/>
                </states>
            </template>
            <template id="3">
                <template-text use-for-branch-template="false">{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "${capitalise(buildStateDescription)} : ${buildName} &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "${capitalise(buildStateDescription)} : ${buildName} build #${buildNumber}", 
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</template-text>
                <branch-template-text>{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "${capitalise(buildStateDescription)} : ${buildName} [${branchDisplayName}] &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "${capitalise(buildStateDescription)} : ${buildName} [${branchDisplayName}] build #${buildNumber}", 
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Branch", "value" : "${branchDisplayName}", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</branch-template-text>
                <states>
                    <state type="beforeBuildFinish" enabled="true"/>
                </states>
            </template>
            <template id="4">
                <template-text use-for-branch-template="false">{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "Failed : ${buildName} &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "Failed : ${buildName} build #${buildNumber}",
            "color": "danger",
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</template-text>
                <branch-template-text>{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "Failed : ${buildName} [${branchDisplayName}] &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "Failed : ${buildName} [${branchDisplayName}] build #${buildNumber}", 
            "color": "danger",
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Branch", "value" : "${branchDisplayName}", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</branch-template-text>
                <states>
                    <state type="buildFailed" enabled="true"/>
                </states>
            </template>
            <template id="5">
                <template-text use-for-branch-template="false">{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "Success : ${buildName} &lt;${buildStatusUrl}|build #${buildNumber}&gt;", 
            "fallback": "Success : ${buildName} build #${buildNumber}", 
            "color": "good",
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</template-text>
                <branch-template-text>{  
    "username": "TeamCity",
    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
    "attachments": [ 
        { 
            "title": "Success : ${buildName} [${branchDisplayName}] &lt;${buildStatusUrl}|build #${buildNumber}&gt;",
            "fallback": "Success : ${buildName} [${branchDisplayName}] build #${buildNumber}", 
            "color": "good",
            "fields" : [
                { "title" : "Status", "value" : "${buildStatus}" },
                { "title" : "Project Name", "value" : "&lt;${rootUrl}/project.html?projectId=${projectExternalId}|${projectName}&gt;", "short": true },
                { "title" : "Build Name", "value" : "&lt;${rootUrl}/viewType.html?buildTypeId=${buildExternalTypeId}|${buildName}&gt;", "short": true },
                { "title" : "Branch", "value" : "${branchDisplayName}", "short": true },
                { "title" : "Commit", "value" : "&lt;${buildStatusUrl}&amp;tab=buildChangesDiv|${substr(build.vcs.number,0,7,32)}&gt;", "short": true },
                { "title" : "Triggered By", "value" : "${triggeredBy}", "short" : true },
                { "title" : "Agent", "value" : "${agentName}", "short" : true }
            ]
        }
    ]
}</branch-template-text>
                <states>
                    <state type="buildSuccessful" enabled="true"/>
                </states>
            </template>
        </templates>
    </webhook-template>
</webhook-templates>

**Comment by netwolfuk** [comment]
Hi @gassanpavel , thanks for taking the time to report this issue. However, I am having trouble reproducing this.
Is there a chance the build name or build number contains a character that is invalid JSON?
Also, is this using the default Slack template that came with tcWebHooks, or has there been modifications done it?

**Comment by gassanpavel** [comment]
Hi @netwolfuk, thanks for quick responce!)
Its default  Slack template.
And, yes, its not valid JSON string
`"value": "Compilation error: ClusterServicePlugins\Swordfish\Swordfish\Swordfish.csproj (new); compilation error: ClusterServicePlugins\VASA\VASA\VASA.csproj (new); compilation error: DAL\DAL.csproj (new); compilation error: VirtualVolumes\VirtualVolumes.cspro..."`

in 

{
	"username": "TeamCity",
	"icon_url": "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png",
	"attachments": [{
		"title": "Failed : ClusterService ",
		"fallback": "Failed : ClusterService build #11",
		"color": "danger",
		"fields": [{
				"title": "Status",
				"value": "Compilation error: ClusterServicePlugins\Swordfish\Swordfish\Swordfish.csproj (new); compilation error: ClusterServicePlugins\VASA\VASA\VASA.csproj (new); compilation error: DAL\DAL.csproj (new); compilation error: VirtualVolumes\VirtualVolumes.cspro..."
			},
			{
				"title": "Project Name",
				"value": "",
				"short": true
			},
			{
				"title": "Build Name",
				"value": "",
				"short": true
			},
			{
				"title": "Commit",
				"value": "",
				"short": true
			},
			{
				"title": "Triggered By",
				"value": "you",
				"short": true
			},
			{
				"title": "Agent",
				"value": "sw-dev-tc-v8",
				"short": true
			}
		]
	}]
}

**Comment by netwolfuk** [comment]
Hi @gassanpavel 
ok, so it's the value in `buildStatus` which is not being handled correctly.

If you have permission to edit the WebHook Templates on your teamcity instance, you could try the following:

Visit `/webhooks/template.html?template=slack.com` in your browser.
You will need to edit the event template for **build failed** and **build broken**, so that the value is escaped.

change the following line 
`                { "title" : "Status", "value" : "${buildStatus}" },`
to
`                { "title" : "Status", "value" : "${escapejson(buildStatus)}" },`

You will need to edit it in four places. Both the **branch** and **non-branch** templates for both the events (**build failed** and **build broken**).

Hopefully, that will escape the JSON string so that it is valid and slack will accept.
Sorry, I can't test this easily, as I don't have an example messy status at the moment.

**Comment by gassanpavel** [comment]
Working)
