### ISSUE TITLE
After Preview & Test, the WebHook Config page will be reset

### ISSUE THREAD

**Issue by alarmz** [tcplugins/tcWebHooks#127]
## Expected Behavior

webHook config page should remember users setting.

## Steps to Reproduce (for bugs)

1. uncheck 
Only trigger when build changes from Failure to Success
and 
Only trigger when build changes from Success to Failure
--
2. click save web hook button
3. refresh web browser
4. edit web hook again
5. click preview & test
6. select a build and do the preview
7. click cancel and exit the edit web hook dialog
8. refresh web page
9. edit web hook again
10. current result
the 
Only trigger when build changes from Failure to Success
and 
Only trigger when build changes from Success to Failure
will be select.

expect result:
Only trigger when build changes from Failure to Success
Only trigger when build changes from Success to Failure
should remember user's config

replay video:
https://www.dropbox.com/s/panwg8kwc0xagqr/clip0025.avi?dl=0

## Your Environment

* tcWebHooks Version:  1.1.261.385
* TeamCity Version:2018.2
* TeamCity server Operating System: windows server 2016
* Are you using a WebHook Template?: YES

**Comment by netwolfuk** [comment]
wow!  Eeek, that's a major bug. Thanks for raising it.

**Comment by skakraze5** [comment]
I've been running into similar issues with the edit dialog not working. It displays fine now. But some of the selections/buttons don't match up with the webhook's actual behavior. I was wondering if it was related to the javascript issues that was root of this: https://github.com/tcplugins/tcWebHooks/issues/123

**Comment by netwolfuk** [comment]
That's a good point. Thanks for mentioning it.

**Comment by netwolfuk** [comment]
It's even worse than suspected. If you look closely after the page is refreshed (at 0:27 seconds) the **Build Events** column says "None"

**Comment by netwolfuk** [comment]
I can re-produce this on TC 2018.1.3
This is a TC webhooks 1.1 bug on all versions of teamcity. It is related to the new testing code, and is probably a pass-by-reference bug.

**Comment by netwolfuk** [comment]
Version released which fixes this bug.
