### ISSUE TITLE
Hook on pinned build

### ISSUE THREAD

**Issue by gregmac** [tcplugins/tcWebHooks#129]
We use pinned builds, especially with tags (eg "beta", "RC", "GA"), to signal releases. It would be handy to get notifications in chat/etc when this happens.

* Add notification event "Build is pinned"
* Add notification event filter for specific tags (stretch goal)

**Comment by netwolfuk** [comment]
Assuming that TeamCity has an extension point for listening to build pins, then this is doable. It is a different type of event, so there will be some plumbing required internally.

Filters might then "just work" with the filter support. No UI for that though.

**Comment by netwolfuk** [comment]
Yes. The open API has `buildPinned` and `buildUnpinned` events, so I guess I should add support for both events.

**Comment by netwolfuk** [comment]
Preliminary support added. When [this build](https://teamcity.jetbrains.com/viewLog.html?buildId=2051825&buildTypeId=WebHooksAndOtherPlugins_TcWebHooks&tab=artifacts) finishes, you can try it out.

There is no support in any templates yet, but you should be able to create a legacy JSON webhook, and have a look at the payload. There is a testing endpoint at `http://<your_teamcity_instance>/webhooks/endpoint.html`, so just point your test webhook at that.

Amongst the payload, you will get...
```
    "buildTags": [
      "Prod_Release"
    ],
    "pinEventUsername": "netwolfuk",
    "comment": "Pinning as prod_release",
```

I might change that data in the payload a bit.
It might be more useful to do something like
```
      "pinEvent": {
          "comment" : "Pinning as prod_release",
          "username": "netwolfuk"
          "type": "pinned"
      },
      "buildTags": [
          "Prod_Release"
      ],
```

**Comment by netwolfuk** [comment]
Btw. I've not done any testing with a filter yet.

**Comment by netwolfuk** [comment]
Hi @gregmac   Did you get a chance to test this, or do you need a template ready for testing?
If so, what "chat" are you using?

**Comment by netwolfuk** [comment]
Released in https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-alpha.2
