### ISSUE TITLE
Enable all triggers for slack

### ISSUE THREAD

**Issue by coolya** [tcplugins/tcWebHooks#13]
Is there any particular reason why I can't customize the events to sent when I select slack JSON payload?

We are running tons of builds a day and I only want to notify the slack channel when the status changes from success to failure and vice versa.

**Comment by netwolfuk** [comment]
The new templates support is still alpha and I haven't implemented all the build events yet. This is the file that needs a few more entries in it. https://github.com/tcplugins/tcWebHooks/blob/custom-templates/tcwebhooks-core/src/main/resources/webhook/teamcity/payload/template/SlackComWebHookTemplate.properties

**Comment by coolya** [comment]
I see.  Is a pull request for adding this welcome? :)

**Comment by netwolfuk** [comment]
Yes. Very welcome. Also, the text in that file needs better wording. One probably expects something better than "all your failures are belong to us" :-)

**Comment by netwolfuk** [comment]
The names of the properties are based on the following https://github.com/tcplugins/tcWebHooks/blob/custom-templates/tcwebhooks-core/src/main/java/webhook/teamcity/BuildStateEnum.java    
You need two versions of each. One with branch in the name and one without. The plugin will choose based on whether your build I'd setup to know about your branches.

**Comment by netwolfuk** [comment]
Hi. I'm just wondering how you got on with those templates. I have a bit of time this weekend so could have a crack at it if you haven't had a chance.

**Comment by netwolfuk** [comment]
@coolya  Do you have slack messages that you think tcWebhooks should emulate? Even a screenshot would be a good start.

**Comment by nbergen** [comment]
FWIW, here's my success message:
```
{
    "text" : "${buildName} SUCCESS",
	"attachments" : [{
            "pretext" : "${buildName} ${projectId} ${branchDisplayName}",
			"fallback" : "${buildName} SUCCESS",
            "title" : "Build Log #${buildNumber}",
            "title_link" : "${buildStatusUrl}&amp;tab=buildLog",
			"color" : "good"
		}
	]
}
```

(with "'s replaced with &quot;, of course)

**Comment by nbergen** [comment]
![image](https://cloud.githubusercontent.com/assets/436882/17633617/0cb6d532-6083-11e6-8f07-72182b91b943.png)

**Comment by netwolfuk** [comment]
Ah. Interesting. I would have made it much more verbose so thanks for the feedback. Maybe it would be a good idea to have a `detailed` and a `compact` version.

**Comment by netwolfuk** [comment]
@nbergen. I presume you are overriding these in `webhook-templates.xml`. Is there a chance you could post that whole file? I'll add them as `compact`.

**Comment by nbergen** [comment]
More terse vertical-space wise, but ran out of time to configure it.

I actually just dropped it in `plugins-settings.xml` for now.  At some point I'll have time to revisit it and clean it up.

```
<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <webhooks enabled="true">
    <webhook url="https://hooks.slack.com/<url>" enabled="true" format="nvpairs">
      <states>
        <state type="buildBroken" enabled="false" />
        <state type="beforeBuildFinish" enabled="false" />
        <state type="buildFailed" enabled="true" />
        <state type="buildFinished" enabled="true" />
        <state type="buildStarted" enabled="false" />
        <state type="responsibilityChanged" enabled="false" />
        <state type="buildInterrupted" enabled="false" />
        <state type="buildSuccessful" enabled="false" />
        <state type="buildFixed" enabled="false" />
      </states>
      <build-types enabled-for-all="true" enabled-for-subprojects="true" />
      <parameters>
        <param name="payload" value="{     &quot;text&quot; : &quot;FAILURE&quot;,  &quot;attachments&quot; : [{             &quot;pretext&quot; : &quot;${projectId} [${branchDisplayName}]&quot;,    &quot;fallback&quot; : &quot;${buildName} FAILED&quot;,             &quot;title&quot; : &quot;Build Log #${buildNumber}&quot;,             &quot;title_link&quot; : &quot;${buildStatusUrl}&amp;tab=buildLog&quot;,    &quot;text&quot; : &quot;${buildName} triggered by ${triggeredBy} has a status of ${buildResult}&quot;,    &quot;color&quot; : &quot;danger&quot;   }  ] } " />
      </parameters>
    </webhook>
    <webhook url="https://hooks.slack.com/<url>" enabled="true" format="nvpairs">
      <states>
        <state type="buildBroken" enabled="false" />
        <state type="beforeBuildFinish" enabled="false" />
        <state type="buildFailed" enabled="false" />
        <state type="buildFinished" enabled="false" />
        <state type="buildStarted" enabled="false" />
        <state type="responsibilityChanged" enabled="false" />
        <state type="buildInterrupted" enabled="false" />
        <state type="buildSuccessful" enabled="true" />
        <state type="buildFixed" enabled="true" />
      </states>
      <build-types enabled-for-all="true" enabled-for-subprojects="true" />
      <parameters>
        <param name="payload" value="{     &quot;text&quot; : &quot;SUCCESS&quot;,  &quot;attachments&quot; : [{             &quot;pretext&quot; : &quot;${projectId} [${branchDisplayName}]&quot;,    &quot;fallback&quot; : &quot;${buildName} SUCCESS&quot;,             &quot;title&quot; : &quot;Build Log #${buildNumber}&quot;,             &quot;title_link&quot; : &quot;${buildStatusUrl}&amp;tab=buildLog&quot;,&quot;text&quot; : &quot;${buildName}  &quot; ,   &quot;color&quot; : &quot;good&quot;   }  ] } " />
      </parameters>
    </webhook>
  </webhooks>
</settings>
```

**Comment by netwolfuk** [comment]
Cool. Thanks so much. I see you're on 0.9.x.x so can't take advantage of the new template features of the 1.1alpha versions. Therefore what you're doing is the best way for that version. I can still take your ideas and use them as the basis for a 1.1 template :-)

**Comment by nbergen** [comment]
As I was trudging around our TC filesystem, I admit I was a little envious of what looks likes UI to edit these in the alpha ;)

**Comment by netwolfuk** [comment]
Don't worry. Not all the ui is done for 1.1 so one still can't actually edit the payload in the ui yet. I'm making progress on the REST api and then can write that ui to talk to that. I just wish I had more time in the evenings.

**Comment by netwolfuk** [comment]
Having said that, choosing from a predefined list of templates does work. And customising templates editing webhook-templates.xml does work.

**Comment by aaronjensen** [comment]
@netwolfuk are there instructions on customizing webhooks-templates.xml? I don't have that file so I'm not sure what would go in it

**Comment by aaronjensen** [comment]
Ah, found an example https://github.com/tcplugins/tcWebHooks/blob/v1.1-alpha6.109.134/tcwebhooks-core/src/test/resources/webhook-templates.xml

I'll try that out. Oh and hi @nbergen, hope all is well 😄

**Comment by netwolfuk** [comment]
This is essentially the same as #61 so once this is done, MatterMost support should just work,

**Comment by netwolfuk** [comment]
@aaronjensen BTW the UI is done in alpha11. So you can edit templates much more easily.
Requires the REST API zip installed as well. See https://github.com/tcplugins/tcWebHooks/wiki/Installing#download-the-plugins

**Comment by netwolfuk** [comment]
I have updated the two templates:
The standard `slack.com` one. Now more verbose:
![image](https://user-images.githubusercontent.com/88687/33641251-a070628e-da99-11e7-8060-a454b535d52a.png)

And the `slack.com-compact` one. Now more terse:
![image](https://user-images.githubusercontent.com/88687/33641310-da06b0c0-da99-11e7-9d2f-f8a30ecb6364.png)
