### ISSUE TITLE
webhooks fail for builds with personal changes

### ISSUE THREAD

**Issue by pgrefviau** [tcplugins/tcWebHooks#132]
## Expected Behavior
Builds that contain personal changes can trigger webhooks successfully.

## Current Behavior
A webhook triggered by an event from a build that contains personal changes fails with the following error message: `Method getVcsRoot() cannot be called for personal build`. This same issue seems to have been mentioned as part of issue #97 's discussion (see [here](https://github.com/tcplugins/tcWebHooks/issues/97#issuecomment-441293795) for specific comment)

I've narrowed the source of this issue to the [the call to getVcsRoot() in the WebHooksChange class](https://github.com/tcplugins/tcWebHooks/blob/v1.1.301.388/tcwebhooks-core/src/main/java/webhook/teamcity/payload/content/WebHooksChange.java#L16). In the usual scenario, the `SVcsModification` instance's concrete type is `jetbrains.buildServer.vcs.impl.DBVcsModification`, which doesn't cause any problems. However, in the case of a build with personal changes, the concrete type is `jetbrains.buildServer.vcs.impl.PersonalVcsModificationImpl`, whose `getVcsRoot` method simply throws an `UnsupportedOperationException` right away.

## Steps to Reproduce (for bugs)
I'm assuming that simply triggering a build with personal changes for a configuration which is configured to fire-off webhooks based on build events should be sufficient.

## Your Environment

* tcWebHooks Version: v1.1.301.388
* TeamCity Version: 2019.2.2
* TeamCity server Operating System: Windows
* Are you using a WebHook Template?: Yes

**Comment by netwolfuk** [comment]
PR merged. To be cherry picked onto `1.1.x.x`, and then I can close this.

**Comment by netwolfuk** [comment]
And a huge thanks to @pgrefviau for the work on this.

**Comment by pgrefviau** [comment]
Glad to help. I should be the one thanking you for creating such an useful and well-built plugin in the first place.

**Comment by netwolfuk** [comment]
Thanks for the feedback. Of course I'm always happy to take PRs if you want to tackle anything else. 😉

**Comment by netwolfuk** [comment]
Thanks for your patience. I have [a build ready for testing](https://teamcity.jetbrains.com/viewLog.html?buildId=2208422&buildTypeId=WebHooksAndOtherPlugins_TcWebHooks&tab=artifacts). If you could give it a go, and let me know then I'll prepare a release.

**Comment by pgrefviau** [comment]
I wasn't able to test on our main server, but I haven't seen any more occurrences of the issue with the new version of the plugin when I tested on a separate server.

**Comment by netwolfuk** [comment]
Ok cool. I'll get a release done as soon as I get a chance. Thanks for your help.

**Comment by netwolfuk** [comment]
released

**Comment by netwolfuk** [comment]
released in 1.2.0 alpha2 too.
