### ISSUE TITLE
teamcity 2019.1 supported ?

### ISSUE THREAD

**Issue by hagaygo** [tcplugins/tcWebHooks#135]
just a question , does teamcity 2019.1 supported ? any issues ?

**Comment by netwolfuk** [comment]
Yes. I've not seen any issues.

**Comment by netwolfuk** [comment]
I just checked and my test system is running tcWebHooks 1.2, so I'll run up a new one with the latest 1.1 release and test.

**Comment by netwolfuk** [comment]
Yep. Seems to be working fine. Please let me know if you find any issues. 

I'll close this ticket.

**Comment by hagaygo** [comment]
Just upgraded to 2019.1.

Everything seems to be working fine.

Thanks for you quick reply.
