### ISSUE TITLE
Project names cause create/edit dialog to fail to show

### ISSUE THREAD

**Issue by Keilaron** [tcplugins/tcWebHooks#137]
Summary:
Create/edit webhook dialog does not show up if a project **name** contains characters not allowed in a Javascript expression, e.g. colons, parentheses, etc.

## Expected Behavior
Dialog should show up when clicking create/edit

## Current Behavior
Clicking create or edit when a "problem" project is present causes a Javascript error to occur, and the only UI change is e.g. the row changing colour.

Thus, project names like the following cause issues:
* Assemble (experimental)
* Staging: Copy backups

Alphanumeric names appear to be fine, along with including spaces, so the following is fine:
* Staging refresh WIP
* Unit tests

`7133815647813188329.js?v=1560903963043:16 Uncaught Error: Syntax error, unrecognized expression: Assemble (experimental)
    at Function.fa.error (7133815647813188329.js?v=1560903963043:16)
    at fa.tokenize (7133815647813188329.js?v=1560903963043:16)
    at fa.select (7133815647813188329.js?v=1560903963043:16)
    at Function.fa [as find] (7133815647813188329.js?v=1560903963043:16)
    at n.fn.init.find (7133815647813188329.js?v=1560903963043:16)
    at new n.fn.init (7133815647813188329.js?v=1560903963043:16)
    at n (7133815647813188329.js?v=1560903963043:16)
    at Object.<anonymous> (-7134507488304462334.js?v=1560903963043:28)
    at Function.each (7133815647813188329.js?v=1560903963043:16)
    at Object.<anonymous> (-7134507488304462334.js?v=1560903963043:28)
fa.error @ 7133815647813188329.js?v=1560903963043:16
fa.tokenize @ 7133815647813188329.js?v=1560903963043:16
fa.select @ 7133815647813188329.js?v=1560903963043:16
fa @ 7133815647813188329.js?v=1560903963043:16
find @ 7133815647813188329.js?v=1560903963043:16
n.fn.init @ 7133815647813188329.js?v=1560903963043:16
n @ 7133815647813188329.js?v=1560903963043:16
(anonymous) @ -7134507488304462334.js?v=1560903963043:28
each @ 7133815647813188329.js?v=1560903963043:16
(anonymous) @ -7134507488304462334.js?v=1560903963043:28
each @ 7133815647813188329.js?v=1560903963043:16
populateWebHookDialog @ -7134507488304462334.js?v=1560903963043:28
showDialog @ -7134507488304462334.js?v=1560903963043:27
showEditDialog @ -7134507488304462334.js?v=1560903963043:27
onclick @ index.html?projectId=(..project ID..):1489`

## Steps to Reproduce (for bugs)
1. Create or edit a project with a **name** to include "unexpected" characters
2. Edit the parent project, go to webhooks
3. Attempt to create or edit a webhook
4. Dialog does not show up. :(

## Environment
* tcWebHooks Version: 1.1.318.391 (upgraded from 1.1-RC1.243.373)
* TeamCity Version: 2017.2.2 (build 50909)
* TeamCity server Operating System: CentOS Linux release 7.6.1810 (Core)
* Are you using a WebHook Template?: Slack.com JSON/compact templates

By the way, part of the reason for the plugin upgrade (we haven't gotten to test the new version yet I think) was that we're looking to resolve the issue where a completed job will result in the webhook reporting "running" instead of "complete" (or success or what have you). At a glance I didn't see any issues regarding this -- has this been experienced / reported?

**Comment by netwolfuk** [comment]
Hi @Keilaron. 

The error you are seeing is possibly because of a recent update working around JS code injection in the page from the Project or Build name. I may have been a bit heavy handed removing possible Javascript characters.

With regards to the "running" vs "complete" text, I found this recently too. Normally I have complicated builds which have a result of "xx tests passed" or something like that. I created a very simple one recently and noticed it to. 

The reason is that the build has not technically completed at the time the webhook fires (it hooks into the finishing event, but a build is not finished until all those event handlers complete), so TeamCity has not set a proper status. I could set it in the payload assembly code, or in the template logic (if a velocity template on 1.2.x). I think doing it in the former location makes more sense. It happens for all events. The most egregious is probably "cancelled" which says it's "running".

Feel free to raise an issue for that. It's a pretty easy fix.

**Comment by netwolfuk** [comment]
@Keilaron , BTW, can I have an example project/build name to test against?

**Comment by Keilaron** [comment]
> The error you are seeing is possibly because of a recent update working around JS code injection in the page from the Project or Build name. I may have been a bit heavy handed removing possible Javascript characters.
Are you sure? This seems like the opposite -- where a string is being interpreted as bare Javascript code rather than being treated as a string (danger!). I haven't tried to isolate where in the code this happens though so I may be mistaken.

**Comment by netwolfuk** [comment]
The commit is  2675215 on the 1.1.x.x branch, but there is a lot to go through.
I'll do some test and see what I can reproduce. Will be next week though, as the plugin competition finishes on Monday.

**Comment by Keilaron** [comment]
I guess it depends on what `c:out` is doing.

**Comment by netwolfuk** [comment]
I suspect it is more likely to be my is code and the hand crafted escape function I wrote.

**Comment by Keilaron** [comment]
How silly of me, I had assumed that was provided and not something you had created! Paying more attention, the solution is simpler -- why are you using `.html(...)` when you clearly aren't trying to actually insert HTML? There's a `.text(...)` function you could use instead in those scenarios. :)

**Comment by netwolfuk** [comment]
Terrific. Thank you for your feedback. I welcome any other suggestions you have. 

Would you be interested in making any changes you can see and submitting a PR? I'm not as well versed in front end stuff.

**Comment by Keilaron** [comment]
I could write a patch or create a PR I suppose, but I wouldn't have an easy way to test/verify it..

**Comment by netwolfuk** [comment]
If you could, that would be great. I'm happy to test it.

**Comment by netwolfuk** [comment]
Hi @Keilaron   Did you get a chance to look into this?

**Comment by netwolfuk** [comment]
I reproduce this on TeamCity 2019.1.1 (build 66192) running tcWebHooks 1.1.318.391.
But not on tcWebHooks 1.2 snapshot (locally). So I'm looking to find what could have changed in the next release.

**Comment by netwolfuk** [comment]
OK, I think I have found it. Ironically, the debug logging was the cause. Removing the logging has resolved it.

**Comment by Keilaron** [comment]
I had cloned it a few hours ago but hadn't started digging in yet.. I'm glad you were able to find it because I wasn't convinced what we were previously talking about was the cause (though I think it would still be good to exchange those functions I mentioned -- they work very similarly so it's a drop-in replacement if you don't need HTML within what's being passed).

**Comment by netwolfuk** [comment]
Thanks for your advice. I will also change those `html()` calls to `text()`.

**Comment by Keilaron** [comment]
I've got a WIP, should I make a PR to 1.1.x.x?

**Comment by netwolfuk** [comment]
Yes please. I can cherry pick onto master once tested.

**Comment by netwolfuk** [comment]
I have rebased/squashed the branch down to a single commit, and then rebased that only the 1.1.x.x. branch. 
Then did a full build, and tested ready for release which has now been done at:
 https://github.com/tcplugins/tcWebHooks/releases/tag/v1.1.326.392

Huge thanks to @Keilaron for all your help and guidance with jQuery.

**Comment by netwolfuk** [comment]
Also released in 1.2.0-alpha.2
https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-alpha.2
