### ISSUE TITLE
Incorrect status ("running") reported by webhook on a finished/finishing build

### ISSUE THREAD

**Issue by Keilaron** [tcplugins/tcWebHooks#138]
_Originally posted by @netwolfuk in https://github.com/tcplugins/tcWebHooks/issues/137#issuecomment-504157488_
> With regards to the "running" vs "complete" text, I found this recently too. Normally I have complicated builds which have a result of "xx tests passed" or something like that. I created a very simple one recently and noticed it too. 
>
> The reason is that the build has not technically completed at the time the webhook fires (it hooks into the finishing event, but a build is not finished until all those event handlers complete), so TeamCity has not set a proper status. I could set it in the payload assembly code, or in the template logic (if a velocity template on 1.2.x). I think doing it in the former location makes more sense. It happens for all events. The most egregious is probably "cancelled" which says it's "running".
>
> Feel free to raise an issue for that. It's a pretty easy fix.

We experience this issue with every build. I think cancelled and error'd builds are reported correctly, but successful ones _always_ show up as "running".

Maybe it would be possible to introduce an async delay to wait for the actual status before reporting the status via the webhook?

**Comment by netwolfuk** [comment]
The result might be hard coded in the slack compact template for non-successful results. I'd need to check that.

**Comment by Keilaron** [comment]
I do see "Success" if I use the preview on a completed build.

**Comment by netwolfuk** [comment]
Yes. That's annoying... https://github.com/tcplugins/tcWebHooks/wiki/Testing-a-WebHook

**Comment by netwolfuk** [comment]
I have the code working for this against 1.2. Do you want a special release against 1.1 as well?

It might be a while before 1.2 is out of beta, so just trying to judge your urgency.

**Comment by netwolfuk** [comment]
Released in https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-alpha.2

**Comment by Keilaron** [comment]
Ah, sorry -- I meant to respond to this sooner. *This* issue I'm not concerned with being released ahead of time (though I would appreciate it of course), and I see you've made another 1.1.x build for the other issue, so I think we're OK for now, thank you. :)

**Comment by netwolfuk** [comment]
I have merged this one against 1.1.x.x too, so if you really want it there should be a build on teamcity.jetbrains.com

I have done a new release yet though as you have already observed.

**Comment by netwolfuk** [comment]
Released
