### ISSUE TITLE
How to use it for google chat?

### ISSUE THREAD

**Issue by artem-tomyuk** [tcplugins/tcWebHooks#147]
Hi, 
is it possible to use it for GoogleChat notifications, it seems there is no valid payload template for it

## Current Behavior
with any available payload format test fails with error:
Error: WebHook endpoint returned non-2xx response (Bad Request) (400)
URL: https://chat.googleapis.com/v1/spaces/...... etc

**Comment by netwolfuk** [comment]
Yes. There is no Google chat template.

Can you please add a link to the documentation for the chat you're using? I found some information about Gsuite hangouts. Is that what you mean?

**Comment by netwolfuk** [comment]
Thanks. If you're a TeamCity administrator, it's easy to create a new template for hangouts.
See  https://github.com/tcplugins/tcWebHooks/wiki/WebHook-Templates-%3A-Web-UI



And the template body should be constructed like this: https://developers.google.com/hangouts/chat/reference/message-formats/basic

**Comment by netwolfuk** [comment]
I just noticed that the wiki I linked to hasn't been updated with the latest version.

It's possible to test your template as you edit it by clicking the preview button and sending a test webhook. This means you can iterate on the payload content without having to run a build.

**Comment by artem-tomyuk** [comment]
Great, thanks for your help, will try it.

пн, 28 жовт. 2019, 17:27 користувач netwolfuk <notifications@github.com>
пише:

**Comment by netwolfuk** [comment]
Hi @artem-tomyuk  
How did you get on with your chat template? 
Do you have a working template you could share?
Can we close this ticket?

**Comment by netwolfuk** [comment]
Closing. Please re-open if you have further queries.
