### ISSUE TITLE
Saving Webhook Event Template Fails with Alert Dialog [Object object]

### ISSUE THREAD

**Issue by jadenz98** [tcplugins/tcWebHooks#152]
## Expected Behavior
When creating a webhook event template, the event template should be saved upon clicking Save Template.

## Current Behavior
An alert dialog appears with the text [Object object], the event template dialog remains, and the event template is not saved.

## Steps to Reproduce (for bugs)
1. Navigate to the Webhook Templates page under **Administration** and click **Add New Template**
2. Enter any legal values for the input fields and click Create button
3. In the new webhook template, select **Add Build Event Template**
4. Select any values and click **Save Template**
5. Alert dialog appears with text **[Object object]** and does not save build event template

## Your Environment

* tcWebHooks Version: 1.1.355.396
* TeamCity Version: 1.1.355.396
* TeamCity server Operating System: Linux
* Are you using a WebHook Template?: Yes

## Example Configuration (xml)
Will provide if needed

**Comment by netwolfuk** [comment]
Hi @jadenz98 can you please take a look at the JavaScript console in your browser and see if there are any errors there?

Open the console and then click save. 
There might be an error shown. There should be the object displayed. Can you have a look and see what the object contains?

**Comment by netwolfuk** [comment]
Also, which browser are you using? Name and version please.

**Comment by jadenz98** [comment]
Here is a screenshot of the error and object I see in the developer console on Google Chrome. If you need more detailed information please let me know.

Also, my browser is Google Chrome version 78.0.3904.97

![Capture](https://user-images.githubusercontent.com/21692626/75906623-f6ba9000-5e14-11ea-9769-c5592431d133.PNG)

**Comment by netwolfuk** [comment]
Hi @jadenz98  I have reproduced this problem. It occurs when the `webapps/ROOT` directory is renamed to `webapps/teamcity` (in your case). 

This changes what's called the "context" in Tomcat. However, the TeamCity REST API does not build the REST API URLs correctly when building the response, and my code just uses the `href` returned by teamcity to build the URL to POST to.

I have raised a bug with TeamCity here: https://youtrack.jetbrains.com/issue/TW-64841

I'll try to come up with a work around over the weekend. I have tried some things today, but have not been successful in correctly generating the `href` references correctly.

**Comment by netwolfuk** [comment]
The response from the TeamCity developers is that this is by design.

I will need to work around it by prefixing the context onto the URL when the rest request is executed.

I'll work on this over the weekend and do a new release to resolve this issue.

**Comment by netwolfuk** [comment]
@jadenz98 A [new release](https://github.com/tcplugins/tcWebHooks/releases/tag/v1.1.357.397) is available, which fixes this bug.

Thanks for taking the time to report it.
