### ISSUE TITLE
SSL handshake errors to https://hooks.slack.com

### ISSUE THREAD

**Issue by jshumaker** [tcplugins/tcWebHooks#155]
## Expected Behavior
Slack incoming webhooks work with the plugin

## Current Behavior
Both trying to preview & test the webhooks, or triggering them from a build results in:
```
Error: Error Unsupported record version Unknown-0.0 occurred while attempting to execute WebHook. (801)
```

checking server logs, it shows this:
```
[2020-04-08 14:55:26,619]   WARN -   jetbrains.buildServer.SERVER - WebHookListener :: :doPost :: An IOException occurred while attempting to execute WebHook (https://hooks.slack.com/services/REDACTED). See the following debug stacktrace
[2020-04-08 14:55:26,620]  ERROR -   jetbrains.buildServer.SERVER - WebHookUserRequestedExecutorImplError Unsupported record version Unknown-0.0 occurred while attempting to execute WebHook.
```

## Steps to Reproduce (for bugs)
1. Add some SSl/HTTPS Certificates to `<Root project>`
2. Create a slack webhook
3. Attempt to test or trigger the webhook.

## Your Environment
* tcWebHooks Version: 1.1.357.397
* TeamCity Version: 2019.2.2
* TeamCity server Operating System: Official Linux 2019.2.2 docker images with Perforce cli added.

The https/ssl certificates were added for ldaps authentication on the server. After doing this, it was observed that some other plugins had issues.  For them however they gave a more expected failure of "unable to find valid certification path to requested target".  tcWebHooks however instead gives the "Unsupported record version", which still seems to be an ssl handshake error.  Adding the certs for hooks.slack.com doesn't seem to affect it.

My best guess as to what is happening is that once the TeamCity server has these keys in a keystore, httpclient is trying to send them as client certificates, and that's causing the broken connection?  In which case rather than using HttpClients.createDefault(), need to override it to some settings where it doesn't send the client certs from the trust store?

**Comment by netwolfuk** [comment]
Thanks for raising this @jshumaker 

I'll try to reproduce this. Could you give me some more details on what certs you added to the JVM? 

Do you need a client cert for LDAP? Which files in the JVM were modified?

**Comment by netwolfuk** [comment]
Oh. Did you add them to TeamCity somehow? I've not seen this option.

**Comment by jshumaker** [comment]
If you edit the root project, there's an "SSL / HTTPS Certificates" section where you can upload custom trusted certificates. I'm not adding client certificates there, only adding CA Root certs for our Windows Active Directory so the ldaps connection is trusted. I then had to add some self-signed certs from a couple internal servers so the vsphere cloud plugin would work with them. In each case those gave errors about no path found for validation. Sadly I can't share those certificates.  Tomorrow I can try and make a test environment to reproduce this using some test certs though.  Should hopefully verify it and provide more concrete reproduction steps for testing.

Java and it's trust stores in general give me massive headaches with this unintentional behavior changes.

**Comment by jshumaker** [comment]
https://www.jetbrains.com/help/teamcity/2019.2/uploading-ssl-certificates.html

That's the documentation on this, fairly limited details.

**Comment by netwolfuk** [comment]
Thanks @jshumaker 

I'll try reproducing this. Thanks for the detailed info. Yeah, I hear you on ssl and java. 

I suspect there are a few things that could be better.

1. The TeamCity cert implementation appears to replace the java trust store, rather than appending to it.
2. tcWebHooks should be failing with the more predictable "valid certification path".
3. If the error really is a client cert issue, it would appear that the certs installed in the root project are also being presented as client certs. This is probably a security issue.

I'll know more once I've had a chance to test it.

**Comment by jshumaker** [comment]
1. It generally appears like it did append to it, most ssl requests are working fine.  The other changed behavior I had was where suddenly self-signed certs it did not complain about previously, it now started to complain about.  So I had to add more trusted certs for those.
2. Agreed, if that is what is happening, but everything I've found thus far suggests it's a different failure path.
3. That was my concern as well.  It's not that bad if the public part of these certs leak for me, but for other people it may be a big issue.

I'm going to see if I can reproduce in a simple test setup and see if I can packet sniff what is actually going on with the ssl handshake. That should verify if it's sending a client cert or more accurately what is going wrong.

**Comment by netwolfuk** [comment]
I just did a very simple test...
1. Installed internal root-ca into Root project.
2. Ran a build which sent a message to slack. 

I'm not able to reproduce this yet. However, a little googling implies that that error could be intermittent. I wonder if it depends on which webserver gets hit on `hooks.slack.com`. Some might have SSL disabled, and only support TLS.

**Comment by jshumaker** [comment]
In my scenario it's not intermittent, happens every time for weeks.  I'm hoping today I can come up with a from-scratch reproduction.  If not I'll try to packet capture from production.

**Comment by netwolfuk** [comment]
Ok, you're probably way ahead of me, but what I would do is:

Spin up a new docker instance and start removing certs from the root project until it works. 

I'm really surprised you needed to add in any certs for slack.

Are you using a proxy to get to slack?

**Comment by netwolfuk** [comment]
@jshumaker If you manage to reproduce it, I'm happy to try your certs if you can get permission to share them. Can send you a gpg public key.

**Comment by netwolfuk** [comment]
I use docker-compose for managing my docker instances.
I added the following to my compose file.

```
    environment:
      JAVA_OPTS: " -Djavax.net.debug=ssl "
```
then with `docker-compose logs -f` I can see the SSL conversation happening with `hooks.slack.com`

**Comment by jshumaker** [comment]
Unfortunately other things came up today so I didn't get a chance to spend more time on this yet.

> I'm really surprised you needed to add in any certs for slack.

I did not have to add any certs for slack.  The certs are added for our companies active directory.  We're using LDAP for the authentication and to connect to it securely, TeamCity needed to accept the cert, which required adding it like this.

**Comment by netwolfuk** [comment]
Ok. Sorry. That was my misunderstanding.
FYI. I'm running the same TeamCity and tcWebHooks version as you, and have not been able to reproduce it. 

I'll wait to hear from you.

**Comment by jshumaker** [comment]
I was going over our configuration further and noticed we're setting jsse.enableSNIExtension to false and I strongly suspect it's causing this.  I'm going to verify behavior in a test and if so close this out.  I suspect we set this option long ago and it's no longer relevant.

**Comment by jshumaker** [comment]
Confirmed, jsse.enableSNIExtension was the cause of this, and unrelated to adding the certificates.  Adding it on test setup reproduces it,  removing it fixes it. No need for adding any certificates.I'm guessing it was instead going from TeamCity 2019.1.3 to 2019.2.2 docker image that caused it to change behavior.  Sorry for bothering you with this, and hopefully anyone else googling this can save some time.

**Comment by netwolfuk** [comment]
Thanks for the update. I'm really glad you found it.

I think the new docker images are based on open jdk rather than oracle. That might be why that flag was causing issues.

I'll have to research what that does.

**Comment by jshumaker** [comment]
It turns off "Sever Name Indication" SSL/TLS extension.  Typically used for virtual hosts by domain name.  hooks.slack.com and likely others most likely require it on?  Several years ago the opposite was true, some hosts broke if you passed it instead of ignoring it.  Some change in behavior around it with the jdk versions though triggered it to start failing for me. Or who knows, maybe it was a change on Slack's part.  I haven't gone back to 2019.1.3 to see how that behaves.

**Comment by Nachiket26** [comment]
Hi,

Is there any update on this? Does removing the entry "-Djsse.enableSNIExtension=false" altogether fix the issue without causing any side-effects?

My setup is a bit old:
TeamCity: 9.1 (build 36973)
Operating system: Linux (2.6.32-504.16.2.el6.x86_64, amd64)
Java: 1.8.0_102-b14 (Oracle Corporation)
Servlet container: Apache Tomcat/7.0.59

and the error is as follows: 

Trace: javax.net.ssl.SSLException: Unsupported record version Unknown-0.0
	at sun.security.ssl.InputRecord.checkRecordVersion(InputRecord.java:552)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:565)
	at sun.security.ssl.InputRecord.read(InputRecord.java:529)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)

Thanks & Regards.

**Comment by jshumaker** [comment]
It definitely fixes the issue. Whether it will cause side effects or not depends upon your specific environment and why you used the option in the first place. In my case it was a specific source control system that had issues with SNI, but that system had been replaced or upgraded to not be an issue years ago.

Most likely it won't cause an issue as everything has updated to properly handle the extension, but if you have any particularly old or buggy https services then it could still be an issue for you.

**Comment by Nachiket26** [comment]
Thanks a lot @jshumaker for the information.

For some strange reason without the change, it started working today evening. But its not consistent yet. So, I'll have to check it anyway. Thanks for your help.
