### ISSUE TITLE
Added to queue event: null buildId 

### ISSUE THREAD

**Issue by nrukavkov** [tcplugins/tcWebHooks#159]
Hello @netwolfuk  😋

## Current Behavior
Event 'added to queue'  generates webhook without buildid. We were expecting to be able to change a tag on a build. But it is not possible, because webhook's payload has a null value in buildId. Is it possible to have some trick and pass a build value?

## Your Environment
* tcWebHooks Version: tcWebHooksPlugin 1.2.0-alpha.6
* TeamCity Version: TeamCity Professional 2020.1 (build 78475)

**Comment by netwolfuk** [comment]
I don't believe an ID has been assigned at this point. My understanding is that the ID is assigned at the started event.

**Comment by nrukavkov** [comment]
> I don't believe an ID has been assigned at this point. My understanding is that the ID is assigned at the started event.

🤔 If you use API to add a new build to queue, teamcity returns build ID and other additional information. And it doesn’t matter has it been started right now or just was added to a queue.

Here is my simple part of PowerShell code which I use to start builds and get their IDs:
```
function Add-ToTeamcityQueue($baseUrl, $buildTypeId, $teamcityEnvVariables , 
$teamcityComment, $username, $password, $tags) {
    $baseUrl = $baseUrl + '/httpAuth/app/rest/buildQueue'
    $payload = @{ buildType = @{ id = "$buildTypeId" }; comment = @{ text = "$teamcityComment" } ; tags = @{ tag = $tags} ; properties = @{property = $teamcityEnvVariables} } 
       
    Send-HttpRequest "$baseUrl" $username $password 'POST' ($payload | ConvertTo-Json -Depth 3)
}
```

```
$response = Add-ToTeamcityQueue $($project.BaseUrl) $($project.ProjectId) $preparedParameters $teamcityComment $TeamcityUsername $TeamcityPassword @(@{ name = $DestinationBranch})
Write-Host "$type build id: " $response.id
```
$response.id has an ID of every build

**Comment by netwolfuk** [comment]
There is an item id. 
http://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/QueuedBuild.html#getItemId--

Is that id the same as the id of the build when it's running/finished?

**Comment by netwolfuk** [comment]
Is the buildTypeid something like bt11 ? If so that is the internal id of the build configuration, not the build instance

**Comment by netwolfuk** [comment]
ok, I found what they are doing. They're getting the promotion and mapping it. I'll need to have a better look when I get to a computer.

https://github.com/JetBrains/teamcity-rest/blob/ad895583981a304d405d0b6ca98f4108782ab5c5/src/jetbrains/buildServer/server/rest/model/build/Build.java#L179-L187

Thanks for raising it. It seems like we can make this better!

**Comment by netwolfuk** [comment]
I've committed a change that copies the promotionId into the buildId field in the Queued webhook events (queue and de-queue).
After it finishes build it will be available to [download from here](https://teamcity.jetbrains.com/buildConfiguration/WebHooksAndOtherPlugins_TcWebHooks?branch=issue-159-null-buildId-for-queued-builds&buildTypeTab=overview&mode=builds).

**Comment by nrukavkov** [comment]
I will take a look on it on Monday. Thank you.

**Comment by netwolfuk** [comment]
Cool. If I get a chance I'll do some more testing too.

**Comment by netwolfuk** [comment]
I have a webservice that receives a LegacyJson webhook request for every build event in my development environment. I can confirm that for every `buildAddedToQueue` event, there is now a `buildId` set. Previous to yesterday, it was null. 

I didn't have any previous `buildRemovedFromQueue` events, but testing that now they are also showing a buildId. From the 17 builds that ran in the last 24 hours, all the buildIds appear to match so I am assuming that the `promotionId` and the `buildId` are the same value.

**Comment by netwolfuk** [comment]
I'd appreciate it if you could keep an eye on the buildId, and let me know if they ever don't match for the other events in the build. However from my little bit of testing, and that comment in the youtrack ticket, I think it should be fine.

**Comment by nrukavkov** [comment]
No problem! I guess everything will be fine. I've tested your fix on a newly installed teamcity and it works. 

Just one case I want to show you. The payload looks like this when there is no agents to start. But I suppose that is fine. You can't definitely know buildId.
```
{
        "embeds": [
            {
                "title" : "Been Added To The Build Queue : test build build #${buildNumber}",
                "url" : "http://localhost:8111/viewLog.html?buildTypeId=bt1&buildId=lastFinished",
                "author" : {
                    "name" : "TeamCity",
                    "url" : "http://localhost:8111/",
                    "icon_url" : "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/teamcity-logo-48x48.png"
                },
                "fields": [
                    
                    { "name" : "Status", "value" : "${buildStatus}", "inline": false },
                    { "name" : "Project Name", "value" : "[test](http://localhost:8111//project.html?projectId=Test)", "inline": true },
                    { "name" : "Build Name", "value" : "[test build](http://localhost:8111//viewType.html?buildTypeId=Test_TestBuild)", "inline": true },
                    { "name" : "Commit", "value" : "[UNRESOLVED](http://localhost:8111/viewLog.html?buildTypeId=bt1&buildId=lastFinished&tab=buildChangesDiv)", "inline": true },
                    { "name" : "Triggered By", "value" : "admin", "inline" : true },
                    { "name" : "Agent", "value" : "${agentName}", "inline" : true }
                ]
            }
        ]
    }
```

None the less I'll get you to know If something goes wrong.

**Comment by netwolfuk** [comment]
Thanks for the update. I didn't really think about it, but I guess it makes sense that the id is allocated when it starts. Otherwise there would be buildIds that are never used when multiple queued events are grouped into a single build.

I'll merge this branch into master and release a new alpha in the next few weeks.

**Comment by nrukavkov** [comment]
@netwolfuk do you have plans to release v1.2?

**Comment by netwolfuk** [comment]
Hi @nrukavkov. Yes. A new alpha will be released this weekend. 

Alpha 7 adds project parameter editing in the UI. Alpha 8 is filter editing in the UI. 

I suspect the final release is still a few months away. But the alphas are very stable.

**Comment by netwolfuk** [comment]
https://github.com/tcplugins/tcWebHooks/projects/2

**Comment by netwolfuk** [comment]
Sorry for the delay. We found bug #167 just before I wanted to release, and I thought it was going to affect all users. 

Alpha 7 will be released this weekend.
