### ISSUE TITLE
Conditional WebHook Execution for Each Build Configuration

### ISSUE THREAD

**Issue by tanyabrytkova** [tcplugins/tcWebHooks#163]
Hi @netwolfuk,

Recently, [new conditional build steps](https://blog.jetbrains.com/teamcity/2020/05/teamcity-2020-1-conditional-build-steps-support-for-kubernetes-slack-notifier-integration-with-azure-devops-and-jira-software-cloud-and-more/#version-2020-1-conditional-build-steps-for-unconditional-versatility) were introduced in Teamcity.

Do you have plans to add the same functionality to the WebHook Config of each build configuration? (like you already have [here](https://github.com/tcplugins/tcWebHooks/wiki/Applying-Filtering-Criteria-To-WebHook-Execution), but for each particular build).

It would be very helpful to be able to configure webhook execution of each build independently, and adding it to UI would eliminate a system administrator's bottleneck in the process.

Thanks in advance,
Tanya.

P.S. We use TeamCity Enterprise 2020.1.2 (build 78726), tcWebHooks 1.1.374.403

**Comment by netwolfuk** [comment]
Hi @tanyabrytkova 

Can you please give me some more information on your use case?

If you're asking if editing filters will be added to the UI, then yes that's on the roadmap for 1.2

If you're asking something else can you please elaborate on your request?

Thanks!

**Comment by tanyabrytkova** [comment]
>If you're asking if editing filters will be added to the UI, then yes that's on the roadmap for 1.2

Yes, thank you!

**Comment by netwolfuk** [comment]
Thanks for the clarification.

I'm currently working on #82. Once that is complete I'll pick up something else. You can see the status of the backlog for the 1.2 release [here] (https://github.com/tcplugins/tcWebHooks/issues?q=is%3Aissue+milestone%3Av1.2+-label%3A%22waiting+for+release%22+is%3Aopen).

**Comment by netwolfuk** [comment]
FYI. UI mockups are in #83

**Comment by netwolfuk** [comment]
Looking at the UI for conditional build steps that's now in TeamCity, I suspect my UI won't be as fancy. I like their drop-down options and stuff, but for the first iteration of filter editing, or will be just an input field.

Maybe I'll look to make it smarter in future releases. It just all takes time.
