### ISSUE TITLE
Invalid message for failed composite builds

### ISSUE THREAD

**Issue by seregamorph** [tcplugins/tcWebHooks#168]
I have a composite build of three dependencies:
![Screen Shot 2020-09-18 at 13 52 44](https://user-images.githubusercontent.com/2844909/93590287-e932b500-f9b6-11ea-909f-77e09d57f9a0.png)

When I execute it and two of three dep fails, the teamcity UI reports looks correct (success 1, failed 2):
![Screen Shot 2020-09-18 at 13 52 09](https://user-images.githubusercontent.com/2844909/93590351-07001a00-f9b7-11ea-8946-f0c7698e7b5d.png)

But the payload (legacy json) has wrong message field `buildStatus`:
```
payload={"build": {
  "buildStatus": "Tests failed: 416 (416 new), passed: 1964; Build chain finished (success: 1, failed: 3)",
  "buildResult": "failure",
  "buildResultPrevious": "success",
  "buildResultDelta": "broken",
  "notifyType": "buildFinished",
```

## Expected Behavior

Message in hook payload should match teamcity UI.

## Current Behavior

Wrong message (illegal count of failed tasks)

## Steps to Reproduce (for bugs)

1. create a composite build of 3 deps
2. run a build that fails on one of three
3.
4.

## Your Environment

* tcWebHooks Version: 1.1.374.403
* TeamCity Version: 2020.1.4 (docker)
* TeamCity server Operating System: docker linux
* Are you using a WebHook Template?: legacy json

**Comment by netwolfuk** [comment]
Hi @seregamorph 

My code is just calling `sBuild.getStatusDescriptor().getText()`. The actual text comes from TeamCity. This looks like it could be a big in TeamCity.

**Comment by netwolfuk** [comment]
Question asked of TeamCity support: https://youtrack.jetbrains.com/issue/TW-67780

**Comment by seregamorph** [comment]
In this case it looks like a bug on the TeamCity side.

**Comment by seregamorph** [comment]
Just for your information. On latest TeamCity 2020.2 I still have this issue:
TeamCity UI message: `Tests passed: 1400; Build chain finished (success: 2, failed: 1)`
Notification text: `Tests passed: 1400; Build chain finished (success: 2, failed: 2)`
Will dup this message to YouTrack

**Comment by netwolfuk** [comment]
I don't think there is anything I can do to resolve this issue. Hopefully they can fix it in TeamCity.
