### ISSUE TITLE
Experimental UI buildStatusUrl

### ISSUE THREAD

**Issue by ghost** [tcplugins/tcWebHooks#177]
For Legacy JSON webhook there is `buildStatusUrl` field, that looks like
```json
"buildStatusUrl": "http://host:port/viewLog.html?buildTypeId=RestApiFramework_VerifyStage_2&buildId=5886",
```
Enhancement proposal: support also new experimental UI URL in a separate parameter. It is formatted with same parameters, but differs a bit:
`http://host:port/buildConfiguration/RestApiFramework_VerifyStage_2/5886?`

**Comment by netwolfuk** [comment]
Hi @schernov-xo  This is a great suggestion. Thanks!

The new UI is called Sakura, so a good name might be `buildStatusSakurUrl`.

In the mean time, it's possible to add it into the  `extraParameters` map in the payload, by creating a TeamCity parameter like the following.

![image](https://user-images.githubusercontent.com/88687/106012897-c6f93280-6120-11eb-8a22-25ce2efb5733.png)

For legacy webhooks, it will appear in the `extraParameters` map.

If you're using a template, this variable will be available for use in the template as `${buildStatusSakurUrl}`.

**Comment by schernov-xo** [comment]
Thanks for this clarification. Right now I do it a bit another way - I format the link on the backend side of my webhook. Just wanted to propose enhancement.
