### ISSUE TITLE
Support for more flexibility in Authorization headers

### ISSUE THREAD

**Issue by Snipx** [tcplugins/tcWebHooks#189]
Hi and thank you for your nice plugin!
I was trying to integrate it with Opsgenie (https://www.atlassian.com/software/opsgenie) but faced the following issue: Opsgenie requires `Authorization` header in a bit non-standard format: `Authorization: GenieKey xxxxx-.....-yyyyyy`. So it's almost same as `Bearer` token except that there is a different keyword. Would it be possible to provide a bit more flexibility in the configuration of the authenitcation so that I can specify a custom header and its value? Or at least full custom value of `Authorization` header. 
P.S. Opsgenie API for reference: https://docs.opsgenie.com/docs/alert-api

Thanks!

**Comment by netwolfuk** [comment]
Hi @Snipx 

You should be able to do what you need by using a [custom header](https://github.com/tcplugins/tcWebHooks/wiki/Custom-Headers). It currently requires you to modify the `plugin-settings.xml`. You can do that on the server disk and TeamCity will reload it, or you can modify the file in server diagnostics.

![image](https://user-images.githubusercontent.com/88687/138371770-8ec40ff9-7aff-4e26-bcf9-3e85c5309fcb.png)
