### ISSUE TITLE
Add template for a gitea commit status event

### ISSUE THREAD

**Issue by jan0sch** [tcplugins/tcWebHooks#191]
It would be great to have template(s) to publish commit status events to gitea.

The API is documented here: https://try.gitea.io/api/swagger#/repository/repoCreateStatus

**Comment by netwolfuk** [comment]
Hi @jan0sch. Have you created templates yourself? https://github.com/tcplugins/tcWebHooks/wiki/WebHook-Templates-%3A-Web-UI

If so, you're welcome to create a pull request to share your template at https://github.com/tcplugins/tcWebHooksTemplates

**Comment by jan0sch** [comment]
Oh cool, thanks for the info. I will take a look at it.

**Comment by netwolfuk** [comment]
I just read through the readme for the templates project.

Importing and exporting are much easier than when i wrote those docs. You can now import and export from the action menu on the top right corner of the templates pages.

I'll try to get a chance to update the readme on the weekend.
