### ISSUE TITLE
Branch filter

### ISSUE THREAD

**Issue by nrukavkov** [tcplugins/tcWebHooks#192]
Hello. Sometimes we need to receive webhooks only for a particular branch. For example, we have some build configuration that does some important job. Teamcity users are allowed to use their branches. Also, we want to receive notifications about failed builds in our slack channel using our external web service. The problem is that we got information about all failures in the user's build. It would be very useful to have some filter-branch(may by like in TeamCity `+:staging`)  field that allows sending a webhook only when builds use a particular branch.

**Comment by netwolfuk** [comment]
Hi @nrukavkov 

It is possible to filter a webhook by branch. However it's not very user friendly at the moment.

You can read about it on this page https://github.com/tcplugins/tcWebHooks/wiki/Applying-Filtering-Criteria-To-WebHook-Execution

I am in the middle of refactoring the UI code (JavaScript and jQuery) to include the editing of filters, parameters and headers.

**Comment by netwolfuk** [comment]
For more details on how to edit the file from within the TeamCity UI, see issue #189

**Comment by nrukavkov** [comment]
@netwolfuk thank you. Is it general settings and applicable for all projects? Or it could be redefined for a particular build configuration?

**Comment by netwolfuk** [comment]
@nrukavkov  It's evaluated against the build that the webhook of triggered by.

When you configure a webhook you determine which project a webhook belongs to. Then when the build runs the webhook is triggered, and the filters are evaluated as the webhook is being assembled and are evaluated against the data in that build.

It's therefore applicable to any project that the webhook will trigger on.
