### ISSUE TITLE
an error occurred when trying to edit event template

### ISSUE THREAD

**Issue by RainforestPie** [tcplugins/tcWebHooks#196]
## Expected Behavior

Encountered the same problem as https://github.com/tcplugins/tcWebHooks/issues/124, I want to edit event template for solving the problem.
## Current Behavior

However, an error occurs and the event template cannot be edited normally

## Steps to Reproduce (for bugs)

1. Visit `/webhooks/template.html?template=slack.com` in browser.
2. Try to edit the event template for **build failed**.
![image](https://user-images.githubusercontent.com/53807655/159208298-85e66c99-20de-4503-a892-e9bc4415206f.png)

3. An error occurs and the event template cannot be edited normally.
![image](https://user-images.githubusercontent.com/53807655/159208615-c194b057-1fa8-4894-a54b-ac8bcf0fb2ec.png)

## Your Environment

* tcWebHooks Version: 1.2.0-alpha.4
* TeamCity Version: 2021.2.3 (build 99711)
* TeamCity server Operating System: Windows10
* Are you using a WebHook Template?: Slack.com JSON template

## Example Configuration (xml)

None

**Comment by netwolfuk** [comment]
Hi @RainforestPie   can you confirm that the tcWebHooks rest API plug-in is installed.

If so, can you confirm that the TeamCity server has been restarted since the plugins were installed?

**Comment by RainforestPie** [comment]
@netwolfuk Thanks for such a quick reply! 
I installed the tcWebHooks rest API plug-in, but might not have restarted TeamCity, I will try to restart it now.

**Comment by RainforestPie** [comment]
Woking! Thank you very much!

**Comment by netwolfuk** [comment]
You're welcome. I wish there was a way I could force TeamCity into requesting a restart. I'll see if there is a way to do that. Something about the fact that the rest API inherits from the TeamCity rest API plug-in and also the tcWebHooks plugin means that it doesn't warm load correctly.

Thanks for the feedback that that fixes it.
