### ISSUE TITLE
Plugin completely broken in newest TeamCity

### ISSUE THREAD

**Issue by fury22pl** [tcplugins/tcWebHooks#200]
With TeamCity 2022.04 the plugin is no longer usable. It installs correctly for both this one and the REST API one, but trying to create new webhook template is impossible. The button to create it doesn't do anything. That applies to both copying template and creating brand new one. I need custom JSON payload, but that's totally impossible as all confirmation buttons do not work.

**Comment by netwolfuk** [comment]
Yeah. I've been trying to figure out if there is a way to determine the uptime of TeamCity versus the plug-in. If they're wildly different then recommend a restart. When the plug-in starts, I can't tell if it's the first time unless I create some sort of flag somewhere.

I'll keep thinking about it.

I'll close this ticket.
