### ISSUE TITLE
999 :: Unexpected exception. Please log a bug on GitHub tcplugins/tcWebHooks. Exception was: null

### ISSUE THREAD

**Issue by matt-richardson** [tcplugins/tcWebHooks#204]
## Expected Behavior

Using a project based webhook sensitive parameter for a bearer auth token should work.

## Current Behavior

An error occurs:
```
999 :: Unexpected exception. Please log a bug on GitHub tcplugins/tcWebHooks. Exception was: null
```

Debugging it leads me to [this line](https://github.com/tcplugins/tcWebHooks/blame/master/tcwebhooks-core/src/main/java/webhook/teamcity/payload/content/ExtraParameters.java#L121), where it uses `previous` when it could be `null.` It should be using `newHookParameterModel` instead.

## Steps to Reproduce (for bugs)
1. Add a webhook parameter to your project
<img width="558" alt="image" src="https://user-images.githubusercontent.com/373389/189261213-f895f42e-349c-4492-8931-a685c94153b8.png">
2. Set up a webhook
<img width="656" alt="image" src="https://user-images.githubusercontent.com/373389/189261269-2cc46d01-8ae6-4b27-88df-65354ade3499.png">
3. Enable bearer authentication
<img width="666" alt="image" src="https://user-images.githubusercontent.com/373389/189261308-f4ae6ab6-b1a3-4946-881f-68cb272580e2.png">
4. Run a build 
5. See error on `WebHook Execution History Details` page
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/373389/189261453-cd2717ae-c597-493d-bb76-803bc7dca733.png">

## Your Environment
* tcWebHooks Version: [1.2.0-alpha.8](https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-alpha8)
* TeamCity Version: 2022.04.3
* TeamCity server Operating System: linux
* Are you using a WebHook Template?: yes, but this happens with all of them

**Comment by netwolfuk** [comment]
Yes! You're right. Thank you @matt-richardson 

It looks like a regression from a merge of the two feature branches. It previously was correct [here](https://github.com/tcplugins/tcWebHooks/blame/0f8e28525fffe95463289eacc02611ee4885c149/tcwebhooks-core/src/main/java/webhook/teamcity/payload/content/ExtraParameters.java#L94)

I'll reproduce and check your PR on the weekend. I need to be sure there are not any other sneaky issues of the same ilk. Alpha 9 on the weekend if I can.

**Comment by matt-richardson** [comment]
That'd be great - I've just shipped a thing that is intended to rely on these webhooks, so I'm super keen to get this fixed so I can unblock my other project!

Thanks for your help!

**Comment by netwolfuk** [comment]
Released
https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-alpha9

**Comment by netwolfuk** [comment]
Thanks for your work on it @matt-richardson

**Comment by matt-richardson** [comment]
Wow. You are a legend. Thanks heaps, @netwolfuk!

**Comment by netwolfuk** [comment]
Haha. You did all the work. 😂

**Comment by netwolfuk** [comment]
I forgot to say, thank you for taking the time to test the alpha releases.

**Comment by matt-richardson** [comment]
No worries - my pleasure!

We've deployed the new version, and it's working a treat 🎉 . Thanks again!

**Comment by netwolfuk** [comment]
Release Candidate 1 released https://github.com/tcplugins/tcWebHooks/releases
