### ISSUE TITLE
Impossible to save WebHook configuration for non system admin users

### ISSUE THREAD

**Issue by benventive** [tcplugins/tcWebHooks#208]
## Expected Behavior

When editing a webhook configuration with the rights to edit a project, we should be able to save it properly.

## Current Behavior

When editing a webhook configuration with a user that is not a System Administrator, an error shows up indicating that the user has no write permission on the project. When doing this as a System Administrator, this works perfectly.

## Steps to Reproduce (for bugs)

Using a user with the "Edit Project" permission but who is not part of the System Administrators
1. Navigate to any project
2. Add or edit a webhook
3. Save

Notice the following message appearing:
![image](https://user-images.githubusercontent.com/12036943/206561836-80326784-27b4-439e-a07d-c38c0f00f917.png)

I went digging through the code and it seems to be coming from the [recently added validator](https://github.com/tcplugins/tcWebHooks/commit/f3bddb39d57a34eb83c0a6260623bb6062e20e0b?diff=unified#diff-5f3cde7fe6dba1d02e7bae2915ff27df1f3558afe313094901d34060e0c899ea).

I tried commenting out [the check for the permission on the project](https://github.com/tcplugins/tcWebHooks/blob/master/tcwebhooks-web-ui/src/main/java/webhook/teamcity/extension/util/WebHookConfigurationValidator.java#L105) and it works as expected. I'm not familiar with debugging plugins so I couldn't go further than that. Hope this helps!

Thanks for the great work

## Your Environment

* tcWebHooks Version: [1.2.0-alpha.10](https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-alpha10)
* TeamCity Version: 2020.04.2
* TeamCity server Operating System: Linux
* Are you using a WebHook Template?: Legacy Json

**Comment by netwolfuk** [comment]
Hi @benventive. Thanks so much for taking the time to dig through the code and report this bug.

I'll take some time on the weekend to spin up exact versions of what you're running and look into it.
There is a lot of change in alpha10, and it looks like I missed something so I'll check it.

It doesn't look like there is any code that will have fixed this in rc1, so I'll check it there too. I keep forgetting to test this stuff as a non-admin. Sorry!

**Comment by netwolfuk** [comment]
One other thing that might be interesting, is whether the same issue happens if the REST API is installed, and one edits the webhook from the Build Config page. In that instance the REST API ism used, and it uses a different validator (I think)

![image](https://user-images.githubusercontent.com/88687/206566031-5500d18c-760f-47d4-89d8-ac5a3097853e.png)

**Comment by netwolfuk** [comment]
Thanks @benventive   I was able to reproduce this on the main edit page, but the issue does not appear on the REST API.
I am testing on tcWebHooks 1.2.0-rc1 and TeamCity 2022.10.1

**Comment by netwolfuk** [comment]
Bugfix released @benventive 

https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-rc2

**Comment by netwolfuk** [comment]
Now both the REST API and the UI use the same logic for checking the permissions. Unfortunately not the same code, but at the logic is now consistent.
