### ISSUE TITLE
Managing Webhooks from Top to Bottom

### ISSUE THREAD

**Issue by dirk-frerichs** [tcplugins/tcWebHooks#209]
## Expected Behavior
If I add a Webhook on the top level of a Project should enable to use the same Webhook on the bottom level. 

## Current Behavior
It works only in the defined Project not above (as expected) not below. So establishing a new webhook have to be done manually for all projects which are available in the environment. Any possibility by managing this via RestApi?

## Your Environment

* tcWebHooks Version:  1.2.0-rc.1
* TeamCity Version: 2022.10.1 (build 116934)
* TeamCity server Operating System:  
* Are you using a WebHook Template?: Yes

**Comment by netwolfuk** [comment]
Hi @dirk-frerichs 

The intended behaviour is that all sub-projects inherit a webhook. This is what the  "All Sub-Project Builds" checkbox configures in the second tab of the edit webhook dialog does. Is that option ticked for you?

![image](https://user-images.githubusercontent.com/88687/207670444-a3b69cae-ad3b-4a52-8a5f-f5892528ea83.png)

**Comment by netwolfuk** [comment]
I have just spotted a UI bug where the list of builds to select (shown in the above screenshot as non-bolded) can sometimes contain all the the builds from all sub-projects.

It should only contain builds in the current project. I don't think this is affecting your expected behaviour, but I'll do some testing to confirm.

Also, yes it is possible (since 1.2.0- alpha.10) to add/edit/delete webhooks via the REST API. I can create an example for you. However, I believe we shouldn't need to for your use case since the "All Sub-Project Builds" checkbox should be doing what you want.

**Comment by netwolfuk** [comment]
Release 1.2.0-rc.3 fixes the issue I found with regards to showing all the builds from all sub-projects.

**Comment by dirk-frerichs** [comment]
Tanks for your fast response. I just tested it like that:
![image](https://user-images.githubusercontent.com/57794601/207799344-94f64a0e-168b-470b-919a-ba24f06cabd3.png)

quiete a bunge of layers. So starting from the ThirdLayer it is as expected
![image](https://user-images.githubusercontent.com/57794601/207800613-4d621a99-be76-4f06-9284-6a64423526d0.png)

if I go to the top:
![image](https://user-images.githubusercontent.com/57794601/207801335-d9bdbfb6-4b1a-4532-96e1-99a0aa43e82f.png)

But I cannot configured on the Top Layer in this approach.

**Comment by netwolfuk** [comment]
Hi. Thanks for the detailed explanation.
Based on this I have found a possible bug that only exhibits in a peculiar fashion.

The new webhook is created using a different means than if it was loaded from config in TeamCity restart. When initially created a value is left as null and then webhooks in this state fail to execute. 

However this doesn't happen after a TeamCity restart. This explains why I have not seen this issue before.

I'll do some more testing and try to get a release out tomorrow. In the mean time, if you restart TeamCity, your webhook will probably work as intended. It only appears to affect new webhooks.

**Comment by netwolfuk** [comment]
RC4 released which should fix the issue you're seeing @dirk-frerichs 

https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-rc4
