### ISSUE TITLE
Legacy Webhook Build Failed Template wrong

### ISSUE THREAD

**Issue by markusstephanides** [tcplugins/tcWebHooks#224]
## Expected Behavior

The build failed event should have it's own template for the legacy webhook format and correctly propagate that a build failed.

## Current Behavior

Instead, it uses the same content as the build success event, which results in wrong webhooks being sent about builds that failed, but receivers get the wrong information that the builds succeeded.

## Steps to Reproduce (for bugs)

1. Create a new webbhook using the legacy webhook format
2. Go to the test tab and select a build
3. Select the build failed event
4. Observe that the wrong template is being used

## Your Environment

* tcWebHooks Version: 1.2.4
* TeamCity Version: 2023.05.2
* TeamCity server Operating System: Debian
* Are you using a WebHook Template?: Legacy Webhook

**Comment by netwolfuk** [comment]
Hi @markusstephanides 

When using the "test" feature, most of the content is loaded from the actual build that you use for testing. If that build was successful, then the data in the webhook payload will be the "success" data rendered in a "failure" payload.

To test a failure event, please try using a build that failed as the input.

Please let me know if I misunderstood your question. Thanks.

**Comment by netwolfuk** [comment]
You're welcome. Thanks for using tcWebHooks.
