### ISSUE TITLE
Get Information from Performance Monitor (BuildFeature)

### ISSUE THREAD

**Issue by Super8film87** [tcplugins/tcWebHooks#226]
Hey,

I was just interested if it is possible to get **average, max** for CPU, Disk, Memory from a a build and send the data via web hook to the monitoring? 

I was checking to use the data from the Build Feature Performance Monitor but I don't find any interface. Additional I found https://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/util/DiagnosticUtil.ThreadDumpData.html#getCpuUsage() but I assume this for TeamCity Server, correct? Even I didn't get this running :)

**Comment by netwolfuk** [comment]
Yes, these values will not be available in the context of a build.

**Comment by netwolfuk** [comment]
I had a quick look and I can't see a plugin to export the server data and it doesn't appear to be available via the rest API either

**Comment by Super8film87** [comment]
Ok - so I'll have to use a third party tool :(

**Comment by netwolfuk** [comment]
TeamCity supports Prometheus. That would be a good place to start.
