### ISSUE TITLE
Outdated release on jetbrains marketplace

### ISSUE THREAD

**Issue by alexstaeding** [tcplugins/tcWebHooks#234]
The latest release available on the [jetbrains marketplace](https://plugins.jetbrains.com/plugin/8948-web-hooks-tcwebhooks-/versions) is 1.2.2 which still seems to have some bugs that were fixed in more recent releases such as [1.2.5](https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.5).

It would be nice if the latest version could be uploaded there to streamline the installation and updating process in TeamCity.

**Comment by netwolfuk** [comment]
Thanks for the reminder. I'll sort that out this week.

**Comment by netwolfuk** [comment]
Update submitted. Waiting on approval from Jetbrain.

**Comment by netwolfuk** [comment]
Updated. Thanks.
