### ISSUE TITLE
Sponsorship?

### ISSUE THREAD

**Issue by matt-richardson** [tcplugins/tcWebHooks#243]
Does this project have a sponsorship program we can sign up to?
At OctopusDeploy, we find it very useful, and we want to be good OSS contributors, so we'd love to find a way to support this project.

**Comment by netwolfuk** [comment]
I looked into the github sponsorship thing, but I'm quite private and they wanted my name, proof of id, and bank details. At which point it was just "too hard".

A couple of times over the last 15 years, I have shared a Paypal address. I will reach out directly via email if you're interested.

Fortunately I don't live in the EU as it's even more complicated. I was reading about it the other day on Masto. Accepting money puts you into some sort of "paid for work" category and then you have tax obligations and filing requirements if you live there. Mainly Germany I think.
