### ISSUE TITLE
JSON Velocity template produces invalid JSON?

### ISSUE THREAD

**Issue by andreycha** [tcplugins/tcWebHooks#245]
Hi,
I'm using the plugin to post messages to Mattermost. I've added a standard JSON template:

```json
{
    "channel_id": "some_id",
    "message": "##### :red_circle: Build failed\n\n| Build | Branch | Version | Status |\n|:---|:---:|:---:|:---|\n| ${projectName} / ${buildName} | ${branchDisplayName} | #${buildNumber} | [${buildStatus}](${buildStatusUrl}) |"
}
```

Works like a charm:
![image](https://github.com/tcplugins/tcWebHooks/assets/1696046/b25ad08a-6ca7-4ad9-836e-10d4e4bbc788)

Now I wanted to extend it with information from `$(changes)` variable using Velocity and switched the template payload format to JSON Velocity. I haven't done any changes in the template text itself, but Mattermost already started to return 400 Bad Request and preview started to also give an error:

![image](https://github.com/tcplugins/tcWebHooks/assets/1696046/ba14c10a-2898-43bd-959a-874ddf4692d6)

Checked the documentation once again but didn't find anything. Would be grateful if you can point to where the issue is. Plugin version is 2.0.0.

**Comment by netwolfuk** [comment]
A couple of interesting things here:
1. Editing the template and then testing from the Template editor half works. At least it doesn't give that json exception
2. Testing from the webhook edit dialog gives me the same as you.

However, if I remove the `####` from the template it works ok.
I think `#` is a keyword in velocity. Does it need to be there for mattermost?
Oddly, it is fine for the build number, but not the set at the beginning.

![image](https://github.com/tcplugins/tcWebHooks/assets/88687/3fdbaf40-2d8e-4ad8-8498-fef9462b48de)

**Comment by netwolfuk** [comment]
So this is what I have and it's working for me...

```
{
    "channel_id": "some_id",
    "message": ":red_circle: Build failed\n\n| Build | Branch | Version | Status |\n|:---|:---:|:---:|:---|\n| ${projectName} / ${buildName} | ${branchDisplayName} | #${buildNumber} | [${buildStatus}](${buildStatusUrl}) |"
}
```
