### ISSUE TITLE
Add example webhook payloads to the documentation

### ISSUE THREAD

**Issue by gerryhernandez** [tcplugins/tcWebHooks#29]
There isn't a single example in the docs. It would be nice to have a reference, especially since it's very difficult to prototype with Team City if you're not an administrator or have other constraints at your organization.

Thanks.

**Comment by netwolfuk** [comment]
Yes. Good point. There are a few various examples on the [blog](https://netwolfuk.wordpress.com/category/teamcity/tcplugins/tcwebhooks/).
Of course, the new templating and UI would make this less error prone, but that's coming along slowly at the moment.
Which version would you like examples for? 0.9 or 1.1?

**Comment by gerryhernandez** [comment]
We're using 0.9 at the moment, but that's just us. We're also trying to use JSON payloads, which don't seem to have any examples on the blog. Really, my suggestion with this issue is to move examples and documentation into the Git repository so it can live alongside the source code. Or at least in the wiki.

By the way, the UI doesn't actually show the version. I had to ask our admin to find the version. Not a big deal, but thought I'd point that out for the next time you need to provide support. :)

Thanks!

**Comment by netwolfuk** [comment]
Thanks again for your feedback.
I guess you're talking about examples on how to configure the webhook to send a specific payload, but I realise there are no actual examples of what you should expect from the default payloads either.

**Comment by netwolfuk** [comment]
I have created a few new pages on the wiki showing examples of what to expect from 0.9
https://github.com/tcplugins/tcWebHooks/wiki/Example-Webhook-output

**Comment by gerryhernandez** [comment]
Thanks a lot! In my case, due to some really annoying constraints, I ended up having to jump through a couple hoops to take a look at the payload through a mock service. The examples you added will definitely save some time for the next person.

**Comment by netwolfuk** [comment]
Great. Thanks for the feedback.
