### ISSUE TITLE
Expose all the configuration options in the UI

### ISSUE THREAD

**Issue by hotgazpacho** [tcplugins/tcWebHooks#3]
I run a TeamCity server with multiple projects on it. It's really a pain to have to root around the filesystem of the server to update things like the custom templates and extra parameters for each project.

It would be very helpful to expose these options in the Web UI.

**Comment by netwolfuk** [comment]
I'm making some good progress on this. See issue #8

**Comment by netwolfuk** [comment]
Need to support:

- [ ] Authentication
- [ ] Custom Parameters
- [ ] Filters

**Comment by flcdrg** [comment]
+1 for filters - now that I've just started using them and discovered I will lose them if I use the UI to edit the template.

**Comment by netwolfuk** [comment]
Any edits you make to the XML will still be kept even if you edit via the UI.

**Comment by flcdrg** [comment]
Hmm.. that didn't seem to be my experience. I'll check again, and log a new issue if I can reproduce it

**Comment by netwolfuk** [comment]
Yes. Please do

**Comment by netwolfuk** [comment]
BTW. Templates are stored in a different file. They are referenced by a webhook.

**Comment by netwolfuk** [comment]
Release candidate 1 released https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-rc1
