### ISSUE TITLE
Support NTLM authentication

### ISSUE THREAD

**Issue by netwolfuk** [tcplugins/tcWebHooks#33]
As per comments in issue #19

**Comment by netwolfuk** [comment]
There should be an artifact [here](https://teamcity.jetbrains.com/viewType.html?buildTypeId=WebHooksAndOtherPlugins_TcWebHooksBranch09xX&branch_WebHooksAndOtherPlugins=issue_33-support_ntlm_auth&tab=buildTypeStatusDiv) soon.

You're welcome to give it a try. I don't have any Windows machines at home (fortunately), so can't test it (unfortunately).

You will need to configure the following:
```
      <auth enabled="true" type="ntlm" preemptive="true">
        <auth-parameters>
          <param name="password" value="password" />
          <param name="username" value="name" />
          <param name="domain" value="domain" />
          <param name="originator" value="teamcity.internal.company.net" />
        </auth-parameters>
      </auth>
```
The new magic is [here](https://github.com/tcplugins/tcWebHooks/blob/issue_33-support_ntlm_auth/tcwebhooks-core/src/main/java/webhook/teamcity/auth/NTLMAuthenticator.java#L23-L42):

**Comment by alexvaccaro** [comment]
Cool, I'll give it a try later this week.

**Comment by netwolfuk** [comment]
Hmm, looks like there will be another release soon ;-)  This one is broke. I'll post again here when it's working.

**Comment by netwolfuk** [comment]
OK, let's try again :-)  Download from [here](https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/774180:id/tcWebHooksPlugin-1.1.87.125.zip)

**Comment by alexvaccaro** [comment]
Unfortunately I couldn't get it to work, I see the service call getting 401 responses. 
I'll try enabling debug logging in TC to see if that sheds any light, but it's not urgent for me so it might take me some time before I try this again.

Many thanks anyway for getting this in :)

**Comment by netwolfuk** [comment]
Sorry about that. If I can figure out a way to do some testing I'll try again, but please do let me know if you can share any insights.

**Comment by netwolfuk** [comment]
I just pushed support for NTLM. Since we last talked about this, Apache Componnts HttpClient has added support directly to the client. So I've updated to the latest version and added the required code. Much easier than last time I looked at it.

Can someone reply here if they want to test it? I've not been able to, since I don't have access to any windows machines.
