### ISSUE TITLE
Resolving of build parameters seems to not work in 1.1-alpha5.81.121

### ISSUE THREAD

**Issue by panrafal** [tcplugins/tcWebHooks#34]
I have a custom template like this:
```
{
"notifyType": "${notifyType}"
"config": "${config}",
"sha": "${build.vcs.number}"
}
```

where `config` is a build parameter. The resulting payload is unfortunately this:

```
{
"notifyType": "buildStarted",
"config": "UNRESOLVED",
"sha": "UNRESOLVED"
}
```

Only a predefined `notifyType` got unresolved. I've checked that `wehbook.*` works too. But none of build parameters or `env.*` get resolved. Is it still possible with templates? Is there any workaround?

I'm on TeamCity 9.1.4, the same happens with nvpairs format.

**Comment by netwolfuk** [comment]
Thanks for reporting this bug. Variable resolution is certainly supposed to still work in 1.1.x.x.
I'll try to take a look this week.

**Comment by netwolfuk** [comment]
Hi. Can I have a bit more info please?
1. Where are you defining the template? Inside with the plugin-settings.xml or in webhook-templates.XML
2. Which payload format are you using?
3. Which build event is this related to? buildStarted , buildSuccessful, etc

Perhaps you could attach example plugin-settings.xml (with sensitive bits removed if applicable).

Thanks.

**Comment by netwolfuk** [comment]
Assuming you're specifically taking about buildStarted this may be related to issue #29

**Comment by panrafal** [comment]
Hi,
The template is defined in webhook-templates.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<webhook-templates>
	<webhook-template enabled="true" name="frontendtooling" rank="30">
		<template-description>Frontend Tooling webhook</template-description>
		<template-tool-tip value="This is some tooltip text for the Test XML Template"/>
		<formats>
			<format name="jsontemplate" enabled="true" />
		</formats>

		<default-template>{
			"notifyType": "${notifyType}",
			"buildId": "${buildId}",
			"buildTypeId": "${buildTypeId}"
		}</default-template>
		<default-branch-template>{
			"notifyType": "${notifyType}",
			"buildId": "${buildId}",
			"buildTypeId": "${buildTypeId}",
			"buildStatus": "${buildStatus}",
			"config": "${config}",
			"appVersion": "${builder.appVersion}",
			"sha": "${build.vcs.number}"
		}</default-branch-template>

		<templates>
		</templates>
	</webhook-template>
</webhook-templates>
```

It's a single default template. When I had it as a template in `<templates>` it was exactly the same.

I get `UNRESOLVED` for `config` (predefined build parameter), `appVersion` (parameter set during build) and `sha` (built-in parameter). If I define parameters as `webhook.*` - they work properly.

It's the same regardless of `notifyType`, actually it's also UNRESOLVED in template preview.

Hope it helps :)

**Comment by panrafal** [comment]
Also, I've checked `nvpairs` in `plugin-settings.xml` and these too were UNRESOLVED...

**Comment by netwolfuk** [comment]
Thank you for the thorough response. This helps a lot.

**Comment by netwolfuk** [comment]
I have finally found the bug and have worked around it, but I am really unhappy with the fix because it leaks a lot of data for the legacy payloads. I will probably change it before the next release.

I have changed it so that [all teamcity build parameters are copied](https://github.com/tcplugins/tcWebHooks/blob/784921d582251ccf0bc9fb5496244fa9ebeb61e7/tcwebhooks-core/src/main/java/webhook/teamcity/payload/content/WebHookPayloadContent.java#L619-L622) into the list available for the resolver. However, that list is also copied into the payload, which leaks all the TeamCity parameters into the webhook payload.

I think I should change the resolver to try finding values in all the parameter maps, but only copy the webhook parameters (which are declared with webhook.* or manually declared in the XML of the webhook). I will try that next.

If you want to try a build, which will probably break again soon, have a look [here](https://teamcity.jetbrains.com/viewLog.html?buildId=788456&buildTypeId=WebHooksAndOtherPlugins_TcWebHooksBranch09xX&tab=artifacts)

**Comment by netwolfuk** [comment]
Sorry for the delay, I have released alpha6. Can you take a look some time and check it solves your issue?
I have been able to get all values filled in by a combination of the following template
```
        <default-template>{
            "notifyType": "${notifyType}",
            "buildId": "${buildId}",
            "buildTypeId": "${buildTypeId}",
            "buildStatus": "${buildStatus}",
            "config": "${config}",
            "appVersion": "${builder.appVersion}",
            "sha": "${build.vcs.number}",
        }</default-template>
```

And declaring the following parameters in the build config in TeamCity. These can be at the project level or in a template too.
`config: 	1.2.3.4`

And echoing the following to stdout from within the build.
`##teamcity[setParameter name='builder.appVersion' value='fff']`

Gives the following result:
```
{
  "notifyType": "buildFinished",
  "buildId": "1312",
  "buildTypeId": "TcPlugins_TcWebHooksGitHub",
  "buildStatus": "Tests passed: 127",
  "config": "1.2.3.4",
  "appVersion": "fff",
  "sha": "1490b30550edd592987a4a11e720629932146d90",
}
```

**Comment by netwolfuk** [comment]
@panrafal 
I'll close this as I believe alpha6 fixes it. Re-open if you want me to look into it further.
