### ISSUE TITLE
Escaping special characters in templates

### ISSUE THREAD

**Issue by panrafal** [tcplugins/tcWebHooks#35]
When variables are used in JSON template, special characters (`"`, `{}`) are not escaped which may lead to invalid payload. Is there a way to escape them, like `${escape(variable)}`?
I know there is `${sanitize()}`, but couldn't find any information on what it actually does.

**Comment by netwolfuk** [comment]
Yeah, sanitize is just a way to remove odd chars and [replace them with an underscore](https://github.com/tcplugins/tcWebHooks/blob/custom-templates/tcwebhooks-core/src/main/java/webhook/teamcity/payload/util/StringSanitiser.java#L7-L23).

Certainly not a good escaper for what you want.

**Comment by netwolfuk** [comment]
I have added a `${escapejson(variable)}` method to the template engine.
Note: this will probably change to `#escapejson(${variable})` with the upcoming migration to Velocity templates.
BTW, I implemented this using [apache commons lang3 escapeJson](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html#escapeJson(java.lang.String))  which does not escape `{}`. Are you sure that is a requirement?

**Comment by panrafal** [comment]
Cool, I think that the only requirement would be new lines and `"`. Do you plan to release a compiled version with this?

**Comment by netwolfuk** [comment]
Are you sure about new lines? I thought they were valid in json too. 
Yes. I stupidly did both your issues on the same branch, so will just test a better fix for #34 and then push a new release. Hopefully tonight or over the weekend.

**Comment by netwolfuk** [comment]
@panrafal
I'll close this as I believe alpha6 fixes it. Re-open if you want me to look into it further.
