### ISSUE TITLE
Triggering hooks based on branch specification

### ISSUE THREAD

**Issue by jelco** [tcplugins/tcWebHooks#39]
Our build configurations have special deployment steps associated with e.g. staging and production branches, aside from the general tests runners that are executed on every branch. As a form of auditing production deployments, I want to trigger webhooks specifically for the builds on the production branch. Currently I can only filter based on build configuration, not on the branch. Is it doable for you to implement such a filter?

There are two exceptions which are explicitly versioned for releases, which uses tags (with the build configuration set to treat tags as branches). There is a fixed pattern for the tag/branch names, and we'd like to monitor those specific builds as well.

With the ability to e.g. specify a regex pattern we would be able to tackle all of this.

**Comment by netwolfuk** [comment]
It's an interesting proposal. I'm not sure how I'd work it into the ui though. Might have to be an xml hackery option. I'll have a think about where to hook it in.

**Comment by netwolfuk** [comment]
Oh. And the regex is certainly the best option. Maybe something like ```<filter key="teamcity.branchName" regex=".+something\w[1-9]" />```

**Comment by netwolfuk** [comment]
Yeah. I like that approach. Filter for anything that is valid in the payload variable list. Even stuff like key: teamcity.agent.os regex:[Ll]inux

**Comment by netwolfuk** [comment]
Would you want multiple filters?  All must match or just at least one?

**Comment by jelco** [comment]
Great!

I personally don't need multiple filters, but if you're going to support that I'd suggest requiring them all to match. If you want OR-like behaviour, you can always change the regex to do that (e.g. ```/^(regex1|regex2)$/```).

**Comment by jelco** [comment]
Just curious, do you have any idea when you'll be able to pick this up? If you're short on time I might just have a go at this myself and create a PR, but my Java is rather rusty so I'd prefer not to. :)

**Comment by netwolfuk** [comment]
I plan to start this evening. It doesn't feel like a one nighter so hoping to have something for you to test by the end of the weekend. Maybe Friday morning your time.

Can you remind me which version you are running? 0.9 or a 1.1 alpha?

I will go with ANDing the filters. If one needs OR one can create another webhook.

**Comment by jelco** [comment]
Alright, sounds good! According to the TC Admin I'm currently using 1.1.83.122. I think the current install was a custom build because the 1.1 branch didn't have the HTTP authentication fully functional yet when I installed it (something about not fully merging certain changes to the 1.1 branch, see #19), but if that's all been merged now I guess I'm just using the 1.1 branch.

**Comment by netwolfuk** [comment]
Yes, that's there in 89d8178547cef4caa30511e79088634873ac728b merged in #27 

Certainly in custom-templates (aka 1.1 alpha) [here](89d8178547cef4caa30511e79088634873ac728b)

**Comment by netwolfuk** [comment]
Hi @jelco .

Please find [a build to test](https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/826014:id/tcWebHooksPlugin-1.1.115.137.zip) and some [example config](https://github.com/tcplugins/tcWebHooks/blob/6a0e36e6d0929568beb7a60e379eb6cc4734e7b6/tcwebhooks-core/src/test/resources/project-settings-test-all-states-enabled-with-branchNameFilter.xml#L17-L19)

I've done very little re-world testing, but the test coverage covers nearly all the new code.

You can get a list of variables by pointing a webhook at:
 http://_your-teamcity-instance_/webhooks/endpoint.html

**Comment by netwolfuk** [comment]
It appears that editing a webhook in the UI wipes out the files in the XML file.
I will look into that over the weekend.

**Comment by netwolfuk** [comment]
OK, that's all sorted. It turned out I had two versions of the plugins installed on my test server.
So the old version did not have the extra code to handle the `<trigger-filters>` element. It should have failed noisily in the logs, but the new plugin was not actually loading due to a missing item in the spring config file.

Once the old plugin was removed and the Spring config added we were up and running. I've therefore merged the issue_39 branch into the custom-templates branch.

A new version is [available for download](https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/826430:id/tcWebHooksPlugin-1.1.117.136.zip). Please test and let me know how you get on.

I have been testing with the following filter item...
```
      <trigger-filters>
        <filter value="${branchDisplayName}" regex="^issue.+$" enabled="true" />
      </trigger-filters>
```
...to only trigger a webhook on builds for `issue` branches

**Comment by jelco** [comment]
Thanks for your quick work! I'm currently attending a conference for work so unfortunately I don't have time to test right now, but I'll start working on it as soon as I get back at the end of the week.

**Comment by netwolfuk** [comment]
Cool. I want your job :-) Enjoy your conference.

**Comment by jelco** [comment]
So I'm back, and just had a go with it. Works great, everything going right on the first try! :) Thanks for your speedy response on this one, it's much appreciated.

**Comment by netwolfuk** [comment]
Great. Hooray for TDD. Could I get you to do me a favour and just write up some examples on the wiki? Just create a new page.

**Comment by jelco** [comment]
Of course! Just for the filters, or do you want some authentication examples as well? I have uses cases for both so that shouldn't be too difficult. I'll probably have some time in the evening that I can dedicate to it.

**Comment by netwolfuk** [comment]
Cool. Thanks. Filters and auth would be great. I had 5 mins today to start something and started this page. https://github.com/tcplugins/tcWebHooks/wiki/Advanced-Editing-of-tcWebHooks-configuration

**Comment by jelco** [comment]
Just letting you know that I accidentally forgot about this, but I have now set myself a reminder for the weekend.

**Comment by netwolfuk** [comment]
This is fantastic. Thank you. Btw I think there are some optimisations you could make by creating your own templates.
