### ISSUE TITLE
Send webhook requests from a threadpool

### ISSUE THREAD

**Issue by netwolfuk** [tcplugins/tcWebHooks#40]
Webhooks are processed serially and synchronously. The build "runs" until the listeners complete.

If a webhook takes a long time to process (eg, timeout connecting to the server) it holds up the build.

Should consider using a thread pool and/or doing requests asynchronously somehow.

**Comment by netwolfuk** [comment]
I've decided against this. The build taking too long to complete is a good thing. Otherwise unsuccessful webhook postings would go unnoticed.

**Comment by tomasz-grobelny** [comment]
There are situations where we specifically want to ignore errors. Could this at least be an option? Also it could be logged that there were errors.

**Comment by netwolfuk** [comment]
tcWebHooks will always log an error in the teamcity-server.log if the response code is not between 200 and 299. This includes timeouts.

I will reconsider it. I think a happy compromise would be to create a pool of workers and not complete the build until all workers in the pool have completed. 

Initially I thought that I'd just create a pool that consumed webhook "jobs" to process, and it be completely asynchronous to the build.

Threaded workers would (at least initially) be opt in only.

**Comment by tomasz-grobelny** [comment]
The design looks good to me.

**Comment by netwolfuk** [comment]
Looking into this, I found that I could not halt the build until the webhooks have executed, since they are handed over to the TeamCity ExecutorServices.

Since the above discussion was before all the history logging was added, I have now implemented the following:

- Threading is enabled by default
- Webhooks are now completely asynchronous from the build.
- All webhook events are logged to the history page, and also the bottom of the webhooks tab in the buildtype page.
- This became vital once the queue events were added, because the queuing of the build waits for the event listeners to complete.
- Also the same for Responsibility events.

**Comment by netwolfuk** [comment]
This will be released as part of 1.2.0, and the first alpha will be available within the next few weeks.

**Comment by netwolfuk** [comment]
1.2.0 alpha.1 released which includes this fix.
