### ISSUE TITLE
teamcity variables do not work for 'build started' trigger w/ tailored JSON

### ISSUE THREAD

**Issue by DexterHaslem** [tcplugins/tcWebHooks#46]
trying to use any teamcity variables like %teamcity.build.id%, etc in a 'build started' trigger in tailored json are not substituted, the whole body ends up being sent verbatim. all other triggers do get substituted correctly. Is this something that is possible to fix?

**Comment by netwolfuk** [comment]
This is a limitation in TeamCity. TeamCity does not do all variable resolution right at the beginning of the build. See #26

There is a work around where I can manually try to resolve them with a resolver, but I've bit implemented that yet. It would mean parsing the content and picking out variables resolve which would be messy.

My current thinking is to manually resolve any webhook.* build properties defined as part of the build. But as I say. It's on the list but not done yet.

**Comment by DexterHaslem** [comment]
I see, apologize for missing existing issue.

**Comment by netwolfuk** [comment]
That's no problem. I've done that many times. :-)
