### ISSUE TITLE
Enable editing of Authorisation Credentials in the UI

### ISSUE THREAD

**Issue by netwolfuk** [tcplugins/tcWebHooks#50]
Yeah, in the UI.

**Comment by netwolfuk** [comment]
@ofyaniv  I have a version ready first initial testing.  You can download from [here](https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/868373:id/tcWebHooksPlugin-1.1.126.140.zip)

Just login as Guest if asked.

I have found one javascript bug introduced in this release, but I think the auth configuration is working.
Click the `Extra Config` tab and setup the authentication settings.

NOTE: This release is NOT ready for production, but I would like feedback on any issues you find with the authentication editing. I've only done a very small amount of testing.

**Comment by netwolfuk** [comment]
Javascript bug found and resolved.
I have found another bug. Once enabled, authentication cannot be disabled. I have a fair idea where that will be occurring. I will do another test release as soon as I can.

**Comment by ofyaniv** [comment]
Hi 

We have tested the authentication UI at the latest plugin on our dev instance of TeamCity.

It is working like a charm on first attempt!
:-)

Our dev teamcity is now integrated with our backend server orchestrating the entire DevOps cycle!
Next step would be to install the latest plugin on our corporate production Teamcity.

Thank you very much for your agile approach.
Appreciate this very much.

( At our use case, authentication is mandatory. We should not disable authentication... )

Kind Regards,
 Ofer

**Comment by netwolfuk** [comment]
There is a new version to test. Please [download from here](https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/868804:id/tcWebHooksPlugin-1.1.127.142.zip)

This version fixes the two bugs listed above. 

I will endeavour to have a new official alpha release within the next few days. It will incorporate this Authentication Editing and issue #51

**Comment by netwolfuk** [comment]
Fixed in release 1.1-alpha8-140.143
