### ISSUE TITLE
Test endpoint url in documentation missing slash "/" after port

### ISSUE THREAD

**Issue by westshawn** [tcplugins/tcWebHooks#51]
Browse to endpoint-viewer.html
Expected text
`
To have items displayed here, configure a webhook to post to 
http://localhost:8111/webhooks/endpoint.html
`

Actual text:
`
To have items displayed here, configure a webhook to post to http://localhost:8111webhooks/endpoint.html
`

tcWebHooksPlugin-1.1-alpha7.122.138
TeamCity 10.0.1 (build 42078)
CentOS Linux release 7.1.1503

**Comment by netwolfuk** [comment]
D'oh. I suspect my TeamCity URL is configured incorrectly in TeamCity's admin section. Because it had two slashes in my ui until I "fixed" the code.

Thanks for the bug report.

**Comment by netwolfuk** [comment]
Fixed in release 1.1-alpha8-140.143
