### ISSUE TITLE
Add webhook for build queue

### ISSUE THREAD

**Issue by martinskuta** [tcplugins/tcWebHooks#52]
This is more a feature suggestion, but it would be also nice to have two more hooks to monitor build queue, to see that your build is in queue. I imagine two new web hook events:
1. BuildAddedToQueue
2. BuildRemovedFromQueue (this might be actually redundant, because we could use BuildStarted)

Didn't investigate the API of TC if it is feasable, but that we can investigate / discuss here if someone decide to do it.

**Comment by netwolfuk** [comment]
It looks like it will be possible. The [TeamCity OpenAPI](http://javadoc.jetbrains.net/teamcity/openapi/current/) has [BuildServerListener](http://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/serverSide/BuildServerListener.html) methods for [buildTypeAddedToQueue](http://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/serverSide/BuildServerListener.html#buildTypeAddedToQueue(jetbrains.buildServer.serverSide.SQueuedBuild)) and [buildRemovedFromQueue](http://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/serverSide/BuildServerListener.html#buildRemovedFromQueue(jetbrains.buildServer.serverSide.SQueuedBuild,%20jetbrains.buildServer.users.User,%20java.lang.String)).

It's [relatively easy to add](https://github.com/tcplugins/tcWebHooks/commit/ca4e0cfe28eedf9e77f2e3536f6981b498954b91), I just can't promise anything in the next 4-6 weeks.

**Comment by netwolfuk** [comment]
BTW. Build remove from queue is not the same as build started. The former is when a user actively removes a build from the queue, whereas the later means the build has reached the front of the queue and is being started.
I suspect addedToQueue and removedFromQueue will suffer the same problems as buildStarted, in that they don't have changes loaded, or TeamCity variables resolved.

**Comment by martinskuta** [comment]
Cool! @netwolfuk thanks for investigating the feasibility.  There is not pressure to have the feature, it is just nice to have and for our case we don't need much information, for our case it is really just to have a glance in HipChat of what is going on on TC without visiting it directly (as it is hidden by VPN + Firewall).

**Comment by netwolfuk** [comment]
FYI, I have some code working for this. It looks like every build goes:
Added to Queue -> Removed from Queue -> Started.

Removed from queue looks like it fires for all builds, and I'm not sure if it's a great deal of use. There are some other parameters which are passed, like the user who removed the build, but they would only make sense if it was actually removed by a user, and not transitioning to started by TeamCity.

I'll do some more playing and hopefully have an early build of 1.2.0 available to test this week some time.

**Comment by netwolfuk** [comment]
So if the build is started by TeamCity, the "user" will be null, and the "comment" will be "Build started".
I'll need to wire those into the payload, so that we can use them for `<filter>` if needs be.

**Comment by netwolfuk** [comment]
I've decided that `buildRemovedFromQueue` should only trigger if `User` is not null. 
Eg, this is when a user removed the item from the queue themselves. 
Otherwise, it's the same as `buildStarted`, but with a lot less information available about the build.

**Comment by martinskuta** [comment]
> I've decided that buildRemovedFromQueue should only trigger if User is not null.

yeah, I can only agree with that. It makes perfect sense.

**Comment by netwolfuk** [comment]
Also, adding a build to the queue now takes more time, because all the webhooks are processed as part of the action. This ends up hanging the UI when one clicks "Run".

This means that issue #40 is now important.

**Comment by netwolfuk** [comment]
If there are no webhooks configured for this event, then the delay is fairly small, but I have  over 200 webhooks configured on my test system, and lots of them trigger on all build events. Sonic notice this sort of issue. 😉

**Comment by netwolfuk** [comment]
1.2.0 alpha.1 released which includes this fix.
