### ISSUE TITLE
WebHooks always trigger...

### ISSUE THREAD

**Issue by mara0209** [tcplugins/tcWebHooks#54]
With the latest version (1.1-alpha8.140.143) I created a WebHook with Payload Formal Slack.com and 'Trigger when build Fails' as the only 'On Completion'. 

The issue is that I also receive notification when build is Successful...

**Comment by netwolfuk** [comment]
I'm having trouble reproducing this. Are you sure there is not another webhook configured on the project or a parent project?

You could easily test it by changing the URL to http://_your_teamcity_instance/webhooks/endpoint.html?testingSlackNotification in your webhook (or creating a new one) and then going to /webhooks/endpoint-viewer.html to see what is triggered.

**Comment by mara0209** [comment]
Weird... I recreated the webhook and now it is ok...

**Comment by netwolfuk** [comment]
Hmmm. That's weird. Do you happen to have an old copy of plugin-settings.xml ? Sometimes TeamCity creates a numbered copy when it is edited.

**Comment by mara0209** [comment]
Maybe it was a user error also... Checked the settings file, but it only keeps the last 3 files and I did 4 tests :( 
So my original config file was erased...

**Comment by netwolfuk** [comment]
Ok. That's a shame. I don't think there will be anything useful in the teamcity-server.log either unless you had debugging enabled in log4j.

**Comment by mara0209** [comment]
If it ever happen again, I will know what to try. Thanks!
