### ISSUE TITLE
No HTTP Post done

### ISSUE THREAD

**Issue by laurentkempe** [tcplugins/tcWebHooks#6]
Since TC 9.0.5 and 9.1 the plugin stopped working
I updated it to 0.9.29.63 and I still don't see any HTTP Post done on my HTTP Listener.
I had it configured to work with https://www.runscope.com and there also I don't see anything happening till I updated

Any idea?

Thanks!

**Comment by netwolfuk** [comment]
Thanks for posting your issue. I'll take a look over the weekend.
In the mean time, could you try enabling debug logs in TeamCity, and see if there are webhooks related errors in the teamcity-server.log?
Details on how to enable debug logging in TeamCity are here: https://confluence.jetbrains.com/display/TCD9/TeamCity+Server+Logs

**Comment by laurentkempe** [comment]
OK here it is, I think

> [2015-07-17 14:36:32,896]  DEBUG -   jetbrains.buildServer.SERVER - About to process WebHooks for project2 at buildState buildFinished 
> [2015-07-17 14:36:32,896]  DEBUG - tbrains.buildServer.ACTIVITIES - WebHookListener :: Webhook proxy set to null for http://ci.innoveo.com:8888/teamcity 
> [2015-07-17 14:36:32,896]  DEBUG - tbrains.buildServer.ACTIVITIES - WebHookListener :: Webhook proxy set to null for https://dvnvwl87pynb.runscope.net 
> [2015-07-17 14:36:32,896]   WARN - ildServer.util.EventDispatcher - Error in event handler: com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceException:  
> [2015-07-17 14:36:32,896]  DEBUG - ildServer.util.EventDispatcher - Error in event handler 
> com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceException: 
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:64)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
> 	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
> 	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:58)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:225)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:204)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:167)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:116)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:72)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:67)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
> 	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:79)
> 	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
> 	at com.thoughtworks.xstream.XStream.marshal(XStream.java:877)
> 	at com.thoughtworks.xstream.XStream.marshal(XStream.java:866)
> 	at com.thoughtworks.xstream.XStream.toXML(XStream.java:839)
> 	at com.thoughtworks.xstream.XStream.toXML(XStream.java:826)
> 	at webhook.teamcity.payload.format.WebHookPayloadJson.getStatusAsString(WebHookPayloadJson.java:55)
> 	at webhook.teamcity.payload.format.WebHookPayloadGeneric.buildFinished(WebHookPayloadGeneric.java:63)
> 	at webhook.teamcity.WebHookListener.processBuildEvent(WebHookListener.java:116)
> 	at webhook.teamcity.WebHookListener.buildFinished(WebHookListener.java:175)
> 	at sun.reflect.GeneratedMethodAccessor352.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:120)
> 	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.superDispatch(ServerSideEventDispatcher.java:16)
> 	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher$1.run(ServerSideEventDispatcher.java)
> 	at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:1)
> 	at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAsSystem(SecurityContextImpl.java:30)
> 	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.dispatch(ServerSideEventDispatcher.java:10)
> 	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:67)
> 	at com.sun.proxy.$Proxy19.buildFinished(Unknown Source)
> 	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl.finishBuild(RunningBuildsManagerImpl.java:165)
> 	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl$1$1.run(RunningBuildsManagerImpl.java)
> 	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
> 	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl$1.run(RunningBuildsManagerImpl.java)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by netwolfuk** [comment]
Can you please try this build?
https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/530695:id/tcWebHooksPlugin-0.9.32.66.zip

**Comment by laurentkempe** [comment]
I am off but I will a colleague to try it, but it will be only in 8 days.

**Comment by netwolfuk** [comment]
OK, I'll do some more testing and possibly release it as a fix before you are back.
The problem is that the TeamCity implementation of the Branch object has changed and now references other objects which are causing circular references.
This affects the JSON and XML payloads, but not the NVPairs or TailoredJSON format and only presents for VCSs that TeamCity supports with multiple branches (eg, GIT and HG).
I have worked around it by providing my own implementation of the Branch interface and only copying in the values that are relevant.

**Comment by netwolfuk** [comment]
This should now be fixed. See release v0.9.35.72
https://github.com/tcplugins/tcWebHooks/releases/tag/v0.9.35.72

**Comment by lionelplessis** [comment]
The issue we experienced is indeed fixed. Many thanks.

**Comment by netwolfuk** [comment]
You're welcome. Thanks for the feedback.

**Comment by laurentkempe** [comment]
:+1: Excellent! Great job @netwolfuk and thanks to @lionelplessis for testing it!
