### ISSUE TITLE
SSL error - unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by mikeclayton** [tcplugins/tcWebHooks#66]
Hi,

I'm not sure if this is the right place to report this, so let me know if I should post somewhere else instead...

I've installed the tcWebHooks plugin on our TeamCity server (TeamCity Enterprise 9.1.4 (build 37293)) and "WebHooks" appears as a tab on our build configurations. I've configured a build to call the Slack webhooks service on "https://hooks.slack.com/services/xxx/xxx/xxx" for "Build Failed, Build Successful" events, but when these events fire nothing appears in Slack and I see the following error in the teamcity-server.log file:

> [2017-03-27 13:20:32,951]   WARN -   jetbrains.buildServer.SERVER - sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException:
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
> 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
> 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
> 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
> 	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
> 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
> 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
> 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
> 	at org.apache.commons.httpclient.methods.StringRequestEntity.writeRequest(StringRequestEntity.java:146)
> 	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
> 	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
> 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
> 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
> 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
> 	at webhook.WebHookImpl.post(WebHookImpl.java:145)
> 	at webhook.teamcity.WebHookListener.doPost(WebHookListener.java:288)
> 	at webhook.teamcity.WebHookListener.processBuildEvent(WebHookListener.java:82)
> 	at webhook.teamcity.WebHookListener.buildFinished(WebHookListener.java:145)
> 	at sun.reflect.GeneratedMethodAccessor288.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:120)
> 	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.superDispatch(ServerSideEventDispatcher.java:6)
> 	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher$1.run(ServerSideEventDispatcher.java)
> 	at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:31)
> 	at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAsSystem(SecurityContextImpl.java:15)
> 	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.dispatch(ServerSideEventDispatcher.java:5)
> 	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:67)
> 	at com.sun.proxy.$Proxy19.buildFinished(Unknown Source)
> 	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl.finishBuild(RunningBuildsManagerImpl.java:194)
> 	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl$1$1.run(RunningBuildsManagerImpl.java:2)
> 	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
> 	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl$1.run(RunningBuildsManagerImpl.java:2)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
> 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
> 	at sun.security.validator.Validator.validate(Validator.java:260)
> 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
> 	... 41 more
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
> 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
> 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
> 	... 47 more

I've tried adding the slack SSL certificate from https://hooks.slack.com to my ".\TeamCity\jre\lib\security\cacerts" file, as well as the issuing "GeoTrust SSL CA - G3" and "GeoTrust Global CA" certificates, but this hasn't resolved the issue, even after a server restart.

I've spent a couple of days trying to resolve this, but I may be missing something simple. Any help or pointers would be appreciated.

Thanks,

Mike

**Comment by netwolfuk** [comment]
Hi mike. I'll try to reproduce this error.
It looks like you're running Windows.

May I please know:
- Windows version
- Exact Java version   `.\TeamCity\jre\bin\java -version`
- Are you running TeamCity as the system user?

**Comment by netwolfuk** [comment]
Are you using the jre that came with the TeamCity install? It's been a while since i used TC on Windows, so i can't remember how it all fits together.

**Comment by mikeclayton** [comment]
Hello. It's Windows 2008 R2 with Service Pack 1, 64 bit. Java version output is below...

```
C:\Windows\system32>E:\TeamCity\jre\bin\java.exe -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```
Interestingly, a second restart seemed to kick-start the plugin and it's now posting to the Slack WebHooks endpoint ok, but it's still recording the exception in the teamcity-server.log.

**Comment by mikeclayton** [comment]
After a bit of digging, I've realised that the failing build id in the logs belongs to a different team in our company and they've got their own Slack account and API key.

The builds from my team are running ok and calling the Slack WebHooks API successfully with no errors logged in teamcity-server.log, but the builds from the other team are failing and logging the certificate trust error above. They're using Maven (we're using msbuild) so I'm going to guess that the specific java install that they're using java.exe from is *not* the one in the TeamCity folder where I've added the the Slack certificates into the cacerts file.

I'm happy it's working for our team, so please feel free to close this ticket. I'll suggest to the other team that they add the Slack certificates to the cacerts file in their java installation.

Thanks,

Mike

**Comment by netwolfuk** [comment]
I must say, I'm more than a little confused by this behaviour. 

The webhook worker runs within the TeamCity server process (which actually runs inside Tomcat).

The webhook has no relationship with the actual build runner, so there is no way it could be affected by its build runner method.

Unless the other team is running in a different TeamCity instance, it must be using the same JVM as you are to send the httpclient request.
