### ISSUE TITLE
Add a template for Microsoft Teams

### ISSUE THREAD

**Issue by netwolfuk** [tcplugins/tcWebHooks#68]
A good template to copy would be the Slack Compact one. The [Java](https://github.com/tcplugins/tcWebHooks/blob/1.1.x.x/tcwebhooks-core/src/main/java/webhook/teamcity/payload/template/SlackComCompactXmlWebHookTemplate.java) and [XML file](https://github.com/tcplugins/tcWebHooks/blob/1.1.x.x/tcwebhooks-core/src/main/resources/webhook/teamcity/payload/template/SlackComCompactWebHookTemplate.xml) are the ones needed to be copied.

**Comment by netwolfuk** [comment]
@cornz. Could you raise a pull request against the 1.1.x.x branch?

**Comment by cornz** [comment]
Yes sure - will do on 04/15 or 04/16 :+1:

**Comment by netwolfuk** [comment]
That'd be terrific. Thanks.

**Comment by netwolfuk** [comment]
@cornz Did you have any luck with this?

**Comment by netwolfuk** [comment]
Hi @cornz even just a copy of the template you're using would be helpful. Thanks.

**Comment by btzrl6** [comment]
Hello,@netwolfuk.  I see this is classified as help wanted.  In #75 you mentioned you do not have access to Teams to test and evaluate.  Do you need help on this issue as well?

**Comment by netwolfuk** [comment]
Yes please!

**Comment by netwolfuk** [comment]
Moved to milestone 1.2, since we're not making much progress on this.

**Comment by btzrl6** [comment]
Ok, my time is getting more flexible than before.  How can I assist with this?  I need to adapt accordingly from the Slack Java and XML template mentioned above, right?  You never get the PR from the other user, yes?

**Comment by netwolfuk** [comment]
Oh. Good point. I've made progress on the editor since then.

We have two ways to approach this:
1. Send me working JSON for the various build states and I will assemble them into a template which you can easily install and test
2. Build the template yourself using the fancy new editor.

Either way, it would be useful to install 1.1alpha12 (released today) for testing.

You'll need to install the rest API plugin too. The editor UI uses it but it'd also be useful for installing the template if I build it for you.

Do you have administration access on your TeamCity instance(s)?

**Comment by btzrl6** [comment]
I have limited admin access to a 2017.1.3 (build 46961) installation. My colleague indicated in passing, when this came up a week or two ago, he upgraded to the "latest release of the Webhook plugin", so I will venture a guess and say that is v1.1-alpha12.192.263.  I have seen the editor piece, not sure that is the fancy new one.  I will follow up on the REST API plugin, if we have, and if they will allow me to move forward with this.

**Comment by netwolfuk** [comment]
Alpha12 was released today, but alpha11 will also work. To use the rest API you will need TeamCity admin to have write access to the templates file. The exact permission is Permission.CHANGE_SERVER_SETTINGS.

**Comment by netwolfuk** [comment]
The editor lives at `/webhooks/templates.html`. There is currently no way to navigate to it except by typing it in.

**Comment by giacomolozito** [comment]
Hi, I see this one is still open. Just in case it helps, I started using tcWebHooks today precisely to add an integration with MS teams and it works nicely.
This is an example template I have set up (inspired to the flowdock one),
no-branch:
```
{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "summary": "TeamCity - ${buildName} - ${buildResult}",
    "themeColor": "#FF0000",
    "sections": [
        {
            "startGroup": true,
            "title": "<a href=\"${rootUrl}/project.html?projectId=${projectId}\">${projectName}</a> :: <a href=\"${rootUrl}/viewType.html?buildTypeId=${buildTypeId}\">${buildName}</a> # <a href=\"${rootUrl}/viewLog.html?buildTypeId=${buildTypeId}&buildId=${buildId}\"><strong>${buildNumber}</strong></a> has <strong>${buildStateDescription}</strong> with a status of <a href=\"${rootUrl}/viewLog.html?buildTypeId=${buildTypeId}&buildId=${buildId}\"><strong>${buildResult}</strong></a>",
            "activityImage": "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/buildFailed%402x.png",
            "activityTitle": "${buildName} - **${buildResult}**",
            "activitySubtitle": "Triggered by **${triggeredBy}** on agent **${agentName}**"
        }
    ]
}
```
and branch:
```
{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "summary": "TeamCity - ${buildName}-${sanitize(branchName)} - ${buildResult}",
    "themeColor": "#FF0000",
    "sections": [
        {
            "startGroup": true,
            "title": "<a href=\"${rootUrl}/project.html?projectId=${projectId}\">${projectName}</a> :: <a href=\"${rootUrl}/viewType.html?buildTypeId=${buildTypeId}\">${buildName}</a> # <a href=\"${rootUrl}/viewLog.html?buildTypeId=${buildTypeId}&buildId=${buildId}\"><strong>${buildNumber}</strong></a> has <strong>${buildStateDescription}</strong> with a status of <a href=\"${rootUrl}/viewLog.html?buildTypeId=${buildTypeId}&buildId=${buildId}\"><strong>${buildResult}</strong></a>",
            "activityImage": "https://raw.githubusercontent.com/tcplugins/tcWebHooks/master/docs/icons/buildFailed%402x.png",
            "activityTitle": "${buildName} (${sanitize(branchDisplayName)}) - **${buildResult}**",
            "activitySubtitle": "Triggered by **${triggeredBy}** on agent **${agentName}**"
        }
    ]
}
```

These above are for build failures, but for other events such as build success it is just a case of changing themeColor and activityImage accordingly.

**Comment by netwolfuk** [comment]
This looks great. Thanks for your work on this. I'll create a build success version and then bundle it with the next release. 
I'm not yet sure when the next release will be. I'm pretty busy over the next few weeks.

**Comment by netwolfuk** [comment]
Hi @giacomolozito.
Do you have the success templates also done? If so, could you share them?

I have created a [github repo for sharing WebHook Templates](https://github.com/tcplugins/tcWebHooksTemplates). This allows the following benefits:

- the person with the access to the end system (in your case MS Teams) can develop and test a template and share it with the community. 
- templates to be easily shared via a pull request
- allows template updates to happen at a different cadence to the plugin releases
- allows the community to iterate quickly on template development together
- once we have a good stable template developed, we can add it to the tcWebHooks release

Perhaps you could export your Teams template and make pull request to add it?

I have written some Instructions on [exporting templates](https://github.com/tcplugins/tcWebHooksTemplates#exporting-a-webhook-template-from-teamcity).

Let me know if you want help with anything.

**Comment by peppelorum** [comment]
The templates provided by @giacomolozito works fine for me =)

**Comment by netwolfuk** [comment]
Great. Thanks for the feedback @peppelorum

**Comment by netwolfuk** [comment]
I have added a build failed/broken template, and published it as the [Microsoft Teams](https://github.com/tcplugins/tcWebHooksTemplates/tree/master/webhook-templates/microsoft-teams) template on [tcWebHookTemplates](https://github.com/tcplugins/tcWebHooksTemplates) repo.

Pull requests or issues to provide screenshots and install instructions are very welcome. Or if you want to enhance the message or provide templates for the other build events.
