### ISSUE TITLE
1.1-alpha9.155.145 doesn't contain time-out fix

### ISSUE THREAD

**Issue by icy-arctic-fox** [tcplugins/tcWebHooks#70]
We were using this plugin extensively at work for tracking builds and ran into the time-out issue. The builds would hang because a server became unresponsive. Our setup has every build being tracked by an external system. We were excited to find that you fixed it, but quickly saddened to find that the pre-release version doesn't have it.

In the release notes for `1.1-alpha9.155.145` it says the fix is there:
```
Bug fix for HTTP time-outs defaulting to infinity. Now set to 120 seconds
Timeouts can be changed by editing main-config.xml and adding a section similar to the following
```
but we have tested it and the builds still hang. It looks like commit 4f8a9892990861f7f4f402975d3bc19800f7be96 didn't get merged.

We use the pre-release version because we want the custom payload types (Flowdock, Slack, etc.)

**Comment by netwolfuk** [comment]
D'oh!  Thank you! I'll do a new release today.

**Comment by netwolfuk** [comment]
Note to self. One should code in a branch and merge to all working branches.
Merged and building at the moment.

**Comment by netwolfuk** [comment]
New release done. Please let me know if you have any further issues. I have tested this commit now.

**Comment by icy-arctic-fox** [comment]
Thank you! We tested it in our environment and everything works as expected.

**Comment by netwolfuk** [comment]
That's great. Thanks for the feedback.
