### ISSUE TITLE
Filtering on build configuration name doesn't seem to work

### ISSUE THREAD

**Issue by jelco** [tcplugins/tcWebHooks#73]
Some of my webhooks should only be triggered for specific build configurations within a project. I've tried adding a trigger-filter on buildTypeId, buildName and buildFullName, but none of them seem to work. Whenever I add such a filter, the hooks seem to not be triggered for any build anymore, which leads me to believe the values I enter actually evaluate to empty strings on which no regex will match.

Is this supported, and if so, which variable should I use? I'm hoping that if I try something for which I at least know it's supposed to work, I can do some targeted debugging.

**Comment by netwolfuk** [comment]
Do you think this is related to a certain timeframe too? Like #72

**Comment by jelco** [comment]
This seems to occur on all build configs I try it on, so I'm guessing it is not related.

**Comment by jelco** [comment]
I noticed while working on the other issue that TC debug logging gives clear information about the actual value it tests filters on, so I'll see if I can figure out some things by using that debug log. I'll keep you posted.

**Comment by netwolfuk** [comment]
Thanks

**Comment by jelco** [comment]
So this is what it looks like:

```
[2017-08-15 17:14:45,776]  DEBUG -   jetbrains.buildServer.SERVER - WebHook NOT triggered: Filter mismatch: ${buildName} (Run tests and deploy (staging, production)) does not match using regex (CentOS|Debian|deploy) https://.../...
```

Just a thought: I made a point of not including `^` and `$` in this regex so it doesn't require a full string match, but could it be that you're forcing such a match in your code? In that case I should be able to fix it by just adding wildcards around it I guess.

**Comment by netwolfuk** [comment]
I have a suspicion that java adds the `^` and `$` implicitly in a regex match.

**Comment by jelco** [comment]
I've modified the regexes, but I'm not running one of these builds anymore today so I'm not sure when I'm going to be able to test it. I'll get back to you.

**Comment by netwolfuk** [comment]
My [tests](https://github.com/tcplugins/tcWebHooks/blob/custom-templates/tcwebhooks-core/src/test/java/webhook/WebHookImplFiltersTest.java) have `^` and `$` in them, with wildcards as well.

**Comment by jelco** [comment]
I can confirm that adding the wildcard prefix and suffix solves this issue. Maybe something to add to the documentation?

**Comment by netwolfuk** [comment]
Thanks for the feedback. Are you happy for me to close this once I update the docs?

**Comment by netwolfuk** [comment]
Docs added. https://github.com/tcplugins/tcWebHooks/wiki/Applying-Filtering-Criteria-To-WebHook-Execution
