### ISSUE TITLE
Where is the link to `/webhooks/templates.html`

### ISSUE THREAD

**Issue by schancel** [tcplugins/tcWebHooks#87]
Thanks for providing your plugin!  So far it looks promising!

## Expected Behavior
A link somewhere to `/webhooks/templates.html`

## Current Behavior
Can't find any link to this, but was able to infer it from a screenshot

## Your Environment

* tcWebHooks Version: latest
* TeamCity Version: TeamCity Professional 10.0 (build 42002)
* TeamCity server Operating System: MacOS X
* Are you using a WebHook Template?: Not yet

## Example Configuration (xml)
NA

**Comment by netwolfuk** [comment]
Ah. Good point. I'll add it to the next release.  There are quite a few places it can be added.

**Comment by netwolfuk** [comment]
Released
