### ISSUE TITLE
webhook url parametrization

### ISSUE THREAD

**Issue by overquota** [tcplugins/tcWebHooks#88]
## Expected Behavior
After reading https://github.com/tcplugins/tcWebHooks/issues/72 issue we expected to get working url parametrization on Success/Failure builds

## Current Behavior
Seems it's not working in 0.9.35.72 version running on our server

Could you point us, which version we need to get working urls like that:
https://exmaple.com/some_webhook/${hey_param}
payload type: json
configuration property: webhook.hey_param: heyhey

after build finishes, we assume to get HTTP POST on https://exmaple.com/some_webhook/heyhey from teamcity server..

Thank you

**Comment by netwolfuk** [comment]
URL substitution might not have been implemented on 0.9

I'll check the code and confirm for you.

**Comment by netwolfuk** [comment]
Hi @overquota,

I have looked through the code, and the URL is not passed into the variable resolver in 0.9.x

Sorry. I would recommend upgrading to 1.1 alpha15 (to be released in the next day or so).

**Comment by netwolfuk** [comment]
alpha15 now released.
