### ISSUE TITLE
upgrade process

### ISSUE THREAD

**Issue by abelal83** [tcplugins/tcWebHooks#89]
Hello, 

Not an issue as such more just guidance.

We are currently using 1.1-alpha8.140.143, and want to upgrade to the latest version. Is there any particular upgrade plan I need to follow or simply replacing existing files is enough? I want to ensure the current configuration doesn't change.

Thanks!

**Comment by netwolfuk** [comment]
Hi,

Yes. You should be totally fine. 

If you have a `.BuildServer/config/webhook-templates.xml` file it might be wise to back it up, as there is a schema change. However, the file will be upgraded and that code is well unit tested.

You're unilkely to have that file though, as the UI to create it did not exist and you would've had to create it by hand.

Thanks. I'll close this ticket.

**Comment by abelal83** [comment]
thank you @netwolfuk
