### ISSUE TITLE
Add support for custom webhook $(parameters) in Tailored JSON

### ISSUE THREAD

**Issue by elovelan** [tcplugins/tcWebHooks#9]
Since tailored JSON only uses a single TC parameter (``webhook.body``), if for instance you want a custom ``color`` parameter that is different between the *success* and *failure* webhooks, there's no way that I can see to define ``$(color)`` for a specific webhook.

Happy to work on this, just want to have the discussion here first.

**Comment by netwolfuk** [comment]
Funny you should ask that. Recent versions this week (not yet released) have support for two iterations of the template engine. 
Download from: https://teamcity.jetbrains.com/viewType.html?buildTypeId=WebHooksAndOtherPlugins_TcWebHooksBranch09xX
And read the comment here: https://netwolfuk.wordpress.com/2014/09/23/new-tcwebhooks-payload-format-tailored-json/#div-comment-45218

**Comment by netwolfuk** [comment]
This is now in release v0.9.35.74

**Comment by elovelan** [comment]
:+1:
