### ISSUE TITLE
Listing on JetBrains Plugins list

### ISSUE THREAD

**Issue by schancel** [tcplugins/tcWebHooks#91]
Your plugin is far more feature complete (and it actually seems to be in a functioning state) than the other two webhooks plugins listed here: https://confluence.jetbrains.com/display/TW/TeamCity+Plugins

**Comment by netwolfuk** [comment]
I can only see two. Mine is the "original" one. And yes. It doesn't look like the other one has been maintained at all since it won a prize in the plugin competition.

Unfortunately I can't edit that page, just a least it links to my blog, which then links here.

**Comment by netwolfuk** [comment]
BTW, one should now be using https://plugins.jetbrains.com/teamcity rather than that wiki page.

I'll close this. I'm not sure what more I could do.
