### ISSUE TITLE
Latest version sends posts with ISO-8859-1 encoding

### ISSUE THREAD

**Issue by flcdrg** [tcplugins/tcWebHooks#92]
## Expected Behavior
Should use UTF-8 encoding. This is causing issues for 3rd party code that is trying to parse the web hook body.

## Current Behavior
POST appears to be specifying ISO-8859-1 encoding

## Steps to Reproduce (for bugs)
1. Create webhook
2. Use https://requestb.in to create endpoint to track content
3. Start build
4. Refresh requestb.in page, note that it says "application/json; charset=ISO-8859-1"

## Your Environment
* tcWebHooks Version: 1.1-alpha14.214.303 
* TeamCity Version: 2017.1.5 (build 47175)
* TeamCity server Operating System: Windows Server 2012R2
* Are you using a WebHook Template?: Happens either way

**Comment by flcdrg** [comment]
I upgraded from an earlier version which did not seem to have this problem.

**Comment by netwolfuk** [comment]
Yes. I noticed this yesterday too. It's due to the changed Httpclient version. 

I have a fix done locally. I'll try to get a new release this weekend.

**Comment by flcdrg** [comment]
Awesome! 
Would rolling back to an earlier version help in the meantime?

**Comment by netwolfuk** [comment]
Yes.

**Comment by netwolfuk** [comment]
Alpha 13 was the last Release on the old httpclient version.

**Comment by netwolfuk** [comment]
My fix is to send as UTF-8, or more accurately, to use the value returned by `WebHookPayload.getCharset()`

This means the header is: `content-type: application/json; charset=UTF-8`

**Comment by netwolfuk** [comment]
I have a [build available](https://teamcity.jetbrains.com/viewLog.html?buildId=1292795&buildTypeId=WebHooksAndOtherPlugins_TcWebHooks&tab=artifacts) if you want to test alpha15, which has this fix, amongst others.

Just log in as a guest.

**Comment by flcdrg** [comment]
That looks like it's working nicely.

**Comment by netwolfuk** [comment]
Great. Thanks for the feedback.

Unless I find any issues in testing, I'll probably release this build on github as alpha 15.

**Comment by netwolfuk** [comment]
released
