### ISSUE TITLE
Handling "UNDEFINED" for numeric fields

### ISSUE THREAD

**Issue by flcdrg** [tcplugins/tcWebHooks#93]
I have some fields in a JSON structure that I'd like to populate with a numeric values. The tricky bit is that the values that I'm using to populate come from TeamCity build properties that are optional.

Currently if they don't exist, tcWebHooks replaces them with UNRESOLVED. This means I need to add quotes around the ${} placeholder to ensure the JSON is valid.

Is there a way to allow the numeric value to be inserted if it exists, otherwise set it to null or something that doesn't require quoting?

**Comment by netwolfuk** [comment]
Where do you currently get these values? Are they build parameters?

**Comment by flcdrg** [comment]
Essentially. I'm queuing a build via the API and adding these via a `properties` block.

The tricky bit is builds that are run other ways (eg. via a TeamCity trigger) won't have these extra properties.

**Comment by flcdrg** [comment]
Maybe I could add a filter to only trigger the webhook if the properties exist?

**Comment by netwolfuk** [comment]
Ah. Yes. I see what you mean. 

We need a kind of `defaultValue(my.property, some Default)` macro, like the `now` macro.

**Comment by netwolfuk** [comment]
Yes. A trigger would work I think.

**Comment by netwolfuk** [comment]
You'd need a couple of hooks setup, and then check for UNDEFINED as the filter.

I'm pretty sure the value is evaluated before the filter

**Comment by flcdrg** [comment]
I'll give the trigger a go. The `defautValue` would be useful too. I guess it depends how much of a DSL do you want to build into the templates.. You could even have a conditional `if`-style statement to allow a whole block to be either included or excluded.

**Comment by flcdrg** [comment]
Well I guess it would either be UNDEFINED, or if it hadn't been evaluated it would be empty. I'll find out shortly!

**Comment by netwolfuk** [comment]
I started down the road of adding support for velocity as the template engine. But trying to make the DSL backwards compatible with what is already there is a pain. 

I guess as an alternative engine it would be ok, and the user can choose the format they want to template in. The ace editor has support for velocity, so I may look at it again in the future.

**Comment by netwolfuk** [comment]
Sorry. It's not a trigger. I meant to write filter.

**Comment by flcdrg** [comment]
Yes.. I knew what you meant :-)

**Comment by netwolfuk** [comment]
Did filters do what you need it to do?

**Comment by flcdrg** [comment]
Yes, once I put them in the right file they worked just how I wanted 😀

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by netwolfuk** [comment]
Cool. Is this part of the TFS stuff on your blog? Would it be useful to others once you get it all working?

It's possible using the rest API to export a template and then to import it into another TeamCity.

I have created a new repo so the exported templates can be shared with the community. I really need to document the steps.

**Comment by flcdrg** [comment]
Yes it is. I was using one of the built in templates, but it contained far more than necessary. New custom template is much more focused and lightweight.

I'll blog about the improvement soon 😀

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by netwolfuk** [comment]
Cool. Can we close this ticket?

**Comment by flcdrg** [comment]
Yes, we can :-)

**Comment by netwolfuk** [comment]
Cool. Thanks
