### ISSUE TITLE
Filters are lost if you subsequently edit a template using the UI

### ISSUE THREAD

**Issue by flcdrg** [tcplugins/tcWebHooks#94]
## Expected Behavior
Editing the template in the UI should not cause any trigger-filters to be lost

## Current Behavior
trigger-filter block is removed from webhook-templates.xml if template is edited in UI

## Steps to Reproduce (for bugs)
1. Create new template in UI
2. Edit webhook-templates.xml manually and add <trigger-filters> section and save
3. Watch TeamCity log to confirm changes are reloaded
4. Edit template in UI
5. Notice that webhook-templates.xml no longer contains <trigger-filters>

## Your Environment

* tcWebHooks Version: 1.1-alpha15.216.313
* TeamCity Version: 2017.1.5
* TeamCity server Operating System: Windows Server 2012 R2
* Are you using a WebHook Template?: yes

**Comment by flcdrg** [comment]
Just saw your comment on the other issue.. Maybe I'm looking at the wrong file?

**Comment by flcdrg** [comment]
Yes, I am.

**Comment by netwolfuk** [comment]
Filters are defined on a webhook instance in plugin-settings.xml

**Comment by netwolfuk** [comment]
😁
