### ISSUE TITLE
[Edit Webhook] Don't display a default payload content selected 

### ISSUE THREAD

**Issue by wadinj** [tcplugins/tcWebHooks#96]
## Expected Behavior
On edit webhook modal on the first reach of tab "Payload content", the first payload related to the last build is selected (first drop down value) should show up.

## Current Behavior
On edit webhook modal on the first reach of tab "Payload content", the first payload related to the last build is selected (first drop down value) but the payload is not showing up. We have to change the value of the drop down box build history and back to the first one to get the payload.

## Steps to Reproduce (for bugs)
1. Go to Webhook 
2. Go to edit
3. Go to tab payload
4. No payload are display although the first build in drop down "Build history" is selected

## Your Environment
* tcWebHooks Version:1.1-alpha13.203.278
* TeamCity Version: 2017.1.4 (build 47070)
* Chrome Version : 63.0.3239.132 
* Are you using a WebHook Template?: No

**Comment by wadinj** [comment]
I'll check to fix it

**Comment by netwolfuk** [comment]
I did some work on this the other day, which I think made it into alpha15.

**Comment by netwolfuk** [comment]
Also, the tab has been renamed to "Preview and Test", with the intention of trying to squeeze #79 in before final 1.1 release.

**Comment by netwolfuk** [comment]
Now looks like this when it loads:
![image](https://user-images.githubusercontent.com/88687/35365538-f6363b46-01d9-11e8-92f5-3d33782e901a.png)

And like this once one selects a build:
![image](https://user-images.githubusercontent.com/88687/35365564-21c07ed4-01da-11e8-9afc-70f806d36422.png)

**Comment by wadinj** [comment]
Sounds good ! 

Love your work, if I could help, don't hesitate to assign me a feat todo :).
I'll ask the update with alpha 15 as soon as possible for tcWebhook.

Thanks,
Jonathan

**Comment by netwolfuk** [comment]
Thanks for your nice feedback.

Confirmed. It was in alpha15 [here](https://github.com/tcplugins/tcWebHooks/compare/v1.1-alpha14.214.303...master#diff-a8d77352fd66db8fd4aa42500cfa505a)
