### ISSUE TITLE
Teamcity notifies on personal builds

### ISSUE THREAD

**Issue by hagaygo** [tcplugins/tcWebHooks#97]
Hi Everyone,

Just installed latest version (tcWebHooksPlugin-1.1-alpha15.216.313.zip & tcWebHooksPlugin-REST-API-1.1-alpha15.216.313.zip) on our teamcity server (windows , 2017.2.2 (build 50909)).

The setup works just fine (hooking to mattermost 4.7.1).

I Noticed that we are getting notifications for personal builds on team city , i am not sure if this is by design or i am missing some setting to disable this , but this behavior is not desired normally (personal builds is hmm, personal).

Please let me know how and if i can disable the webhooks notifications for personal builds.

**Comment by netwolfuk** [comment]
Thanks @hagaygo. You are right. tcWebHooks listens for all build events from TeamCity and does not differentiate between personal builds and non-personal builds. It's interesting, but I don't think anyone has ever asked this before feature before. It seems obvious now that you have and I will mark this issue as an enhancement request.

By the way: The only time when personal builds are considered differently is when the historical state change is calculated. Personal builds are ignored when finding the most recent build result to determine if the current build has changed (eg, to determine pseudo events like buildBroken and buildFixed).

If you're up for some XML hacking, you may be able to filter out personal builds by adding a [Trigger Filter](https://github.com/tcplugins/tcWebHooks/wiki/Applying-Filtering-Criteria-To-WebHook-Execution).

Have a look at the history of your personal builds, and see of there is a build parameter set by TeamCity. something like `teamcity.build.isPersonal` which you could use as the `filter value` and create an appropriate regex to check for it.

Sorry, I won't get a chance to test this myself today. But let me know if you want further help.

**Comment by hagaygo** [comment]
Thanks for the thorough answer.

I'll give your idea  a try.

Hope to see this implemented in next version as "simple checkbox" :)

**Comment by netwolfuk** [comment]
Yeah, that would be my thinking too. It would default to "on" so as not to surprise users, but can be easily unchecked.

**Comment by netwolfuk** [comment]
I had a look and could not figure out how to extract the personal build status, so I have added it the webhooks payload object as `buildIsPersonal`. It's now possible to use a `filter` to filter out personal builds.

If you want to give [this build](https://teamcity.jetbrains.com/viewLog.html?buildId=1331360&tab=artifacts&buildTypeId=WebHooksAndOtherPlugins_TcWebHooks) a try (or a newer one), you will be able to configure a filter like this (tested by me):

```
          <trigger-filters>
                <filter value="${buildIsPersonal}" regex="^false$" enabled="true"/>
          </trigger-filters>
```

So for now we have a working solution (albiet a bit cumbersome), until the nice UI and toggle is implemented.

**Comment by hagaygo** [comment]
For our main usage (remote runs via visual studio) the current behavior is fine.

I still think there should be an option to disable/enable webhooks for personal build (or it should be always disabled if such option is too complicated)

**Comment by Eric-Pang** [comment]
Is this same issue as shown on the Webhooks tab on TeamCity Server under "Recent WebHook Errors"?

999 :: Unexpected exception. Please log a bug on GitHub tcplugins/tcWebHooks. Exception was: Method getVcsRoot() cannot be called for personal build

**Comment by netwolfuk** [comment]
Hi @Eric-Pang. This feels like a different issue, but could I please get some more information?

Which build event was this for ? Eg, Started, Changes Loaded, Finished, etc.

I've not really looked into this issue in detail. I could be related.

**Comment by netwolfuk** [comment]
Hi @Eric-Pang  Issue #132 has been raised to address your issue. The PR #133 has been merged against master and the plan to patch `1.1.x.x` and release a bugfix over Easter.

@hagaygo There is a chance that this fix will change the behaviour you're seeing, and make personal builds work as I intended (which is not what you actually want). I'll try to find some time to test your use case too.

**Comment by hagaygo** [comment]
Just upgraded to latest version (1.1.374.403) and now i do get notifications for "Remote run" , any way to to disable notifications on "remote run" or "pesronal" builds ?

**Comment by netwolfuk** [comment]
Oooh. I can't remember if I did that or not. I'll need to take a look and see. Hopefully over the weekend. It's been so long since I looked at this, I have forgotten all the context.

**Comment by netwolfuk** [comment]
Hmm. Looks like I didn't do anything to address the concern @hagaygo 

I can't promise I'll get a fix in this weekend, and my next few weekends are hectic. Your best work around for now is the filter above. Does work for you, or am I misinterpreting your request?

**Comment by hagaygo** [comment]
Where do i need to put that filter snippet ? 
can you direct me to the correct place ?

**Comment by netwolfuk** [comment]
The docs are here, https://github.com/tcplugins/tcWebHooks/wiki/Applying-Filtering-Criteria-To-WebHook-Execution

**Comment by netwolfuk** [comment]
Also a detailed step by step to solve a different problem with filters is in #117

**Comment by hagaygo** [comment]
Thanks for the quick help, after adding it to the xml file , remote run did not notify on the webhook.

Hoping to see this in the GUI soon.

**Comment by netwolfuk** [comment]
Yeah. Is quite a bit of work unfortunately. I need to add to the config file and all the logic around reading and writing to that. I need to add it to the UI and all the logic around editing and saving and testing webhooks.
Also need to add to the executor logic, so that the setting is considered during webhook execution.

That's probably why it sat for a while.

**Comment by netwolfuk** [comment]
Editing of filters is in the roadmap for 1.2 though, so on reality that might happen first.

**Comment by netwolfuk** [comment]
Also, FYI. Editing the webhook does preserve filters correctly even though you can't see them in the UI. So if you edit the webhook in the UI and be confident that your manual XML edits will still be there.

**Comment by Edstub207** [comment]
@netwolfuk Any update on this?

**Comment by netwolfuk** [comment]
Hi @Edstub207. Thanks for the reminder. I am really close to having filters (and headers and parameters) editable in the UI. 

At which point adding some quick filters would be relatively easy. I'm thinking the most useful ones would be "is default branch" and "is non-personal build".

**Comment by Edstub207** [comment]
@netwolfuk Thanks, sounds good :)

Do you know how long that might be?

**Comment by netwolfuk** [comment]
@Edstub207 I'm really hoping to have 1.2 alpha 9 out within a month. That will be the last alpha and then a release candidate or two to address any bugs. Are you interested in running a (well tested) pre-release version?

**Comment by Edstub207** [comment]
@netwolfuk Yeah I'm up for testing a pre-release version :)

**Comment by netwolfuk** [comment]
Cool. Thanks @Edstub207.  I'll post here whenever there is a new build on that branch.

**Comment by netwolfuk** [comment]
Hoping to have a build for you to test by the end of the weekend @Edstub207

**Comment by netwolfuk** [comment]
![image](https://user-images.githubusercontent.com/88687/189464157-04508b60-d6b8-4b99-9088-c9cf794edbc5.png)

**Comment by netwolfuk** [comment]
@Edstub207  New builds available for the  [issue_3-add_filters_to_ui](https://teamcity.jetbrains.com/buildConfiguration/WebHooksAndOtherPlugins_TcWebHooks?branch=issue_3-add_filters_to_ui&buildTypeTab=overview&mode=builds) branch

I'm keeping track of issues related to these builds at #206

**Comment by netwolfuk** [comment]
New changes pushed. Build will be available on the above link shortly.

**Comment by netwolfuk** [comment]
New changes pushed. Builds available for the [issue_3-add_filters_to_ui](https://teamcity.jetbrains.com/buildConfiguration/WebHooksAndOtherPlugins_TcWebHooks?branch=issue_3-add_filters_to_ui&buildTypeTab=overview&mode=builds) branch.

**Comment by netwolfuk** [comment]
More new changed pushed. [issue 3](https://teamcity.jetbrains.com/buildConfiguration/WebHooksAndOtherPlugins_TcWebHooks?branch=issue_3-add_filters_to_ui&buildTypeTab=overview&mode=builds)

**Comment by Edstub207** [comment]
Hey, @netwolfuk Sorry about not doing any testing of this - I've had to look at other areas recently. So not sure when/if I can do testing right now.

**Comment by netwolfuk** [comment]
No problem @Edstub207. I've been there. Found a bug last night, but still hoping to get a release out this weekend.

**Comment by netwolfuk** [comment]
Alpha 10 released https://github.com/tcplugins/tcWebHooks/releases

**Comment by netwolfuk** [comment]
Release Candidate 1 released https://github.com/tcplugins/tcWebHooks/releases
